### ISSUE TITLE
Explore adding a concrete Job model

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#1001]
### Environment
* Python version: 3.9
* Nautobot version: 1.1.3

### Proposed Functionality
As Patti the Platform Admin and Cora the Coder, I want Jobs to be stored and manipulated as a concrete model such that Job code and its metadata is stored in the database so that Jobs are portable across many nautobot instances and celery workers, and so more intelligent filtering and manipulation logic can be applied to Job definitions.

### Use Case
Today Jobs live either on the local filesystem (either in NAUTOBOT_ROOT directly, or via git integration), or are provided via plugins. In a larger distributed environment with many nautobot application instances and many celery workers, the local filesystem jobs become very problematic to deal with. Backing jobs by an actual model would solve distributed problems within nautobot, and allow the core git functionality to work as intended in such an environment.

Additionally, it has come up through several other issues lately that a job model would benefit other initiatives like search, tagging, and grouping of jobs. It would also allow an easier implementation of fine-grained access controls, using the existing permissions framework.

### Database Changes
We would need a new concrete model to represent and store jobs, their metadata, and the actual code.

### External Dependencies
None

### To Do

- [ ] Spike: Investigate API Versioning Scheme for Future Enhancements: #1465
- [ ] Update New Jobs Model APIs to Follow API Versioning Scheme (if necessary)

**Comment by glennmatthews** [comment]
As we've discussed this more amongst the team, the idea of storing Job *code* in the database seems relatively infeasible due to the complexities of dependency management (on Nautobot itself as well as on arbitrary third-party libraries that a Job might require). Generally speaking, in a scaled/distributed Nautobot deployment, local-filesystem jobs (manually installed in `JOBS_ROOT`) should be avoided in favor of the more resilient alternatives of Git and plugins. *We should document this recommendation.* 

The real advantages of a concrete Job database model, as I see them, lie in the configuration and management of jobs, mostly independent of the specifics of how a source file is distributed and installed. Specifically, this should make it possible to address the following (many of which are carried over from the epic of #765):

- Jobs (source code) must be discoverable to automatically create corresponding Job (database) records.
    - Sources in `JOBS_ROOT` must be discovered at Nautobot server startup
        - Additionally it may be desirable to have Nautobot monitor the contents of `JOBS_ROOT` while running so as to detect filesystem additions (perhaps via something like `inotify`?) without requiring a server restart
    - Sources in `GIT_ROOT` must be discovered at Nautobot server startup if they correspond to defined Git repositories
    - Syncing a Git repository may trigger Job database additions
    - Sources provided by a plugin must be discovered during plugin loading (i.e. at Nautobot server startup)
- It's not clear at this time whether Job records should be auto-deleted if their corresponding source code is discovered to be unavailable or absent.
    - It might be better to have such jobs be automatically flagged as "not runnable" (see below) or perhaps even add an additional "source available" property?
- Job database records must include an "enabled" or "runnable" boolean flag that can be edited by a user with appropriate access.
    - For security, this should default to False for newly added Jobs.
        - Optionally we could provide a configuration option to change this default value?
    - When this field is False, the corresponding Job (source) cannot be run via the UI, the REST API, or the `nautobot-server runjob` command. An appropriate error must be reported in each case.
    - The Job listing page should be filterable based on the value of this field
    - The Job REST API listing should be filterable based on the value of this field
- The Job database model must support standard Nautobot model features (including but not necessarily limited to tags, custom fields, relationships, and GraphQL)
    - Tag support and custom field support should be sufficient to address #883.
- The Job database model must have a "category" or "grouping" text field that can be edited by a user with appropriate access.
    - For backwards compatibility this field should default to the module `name` attribute, if any, defined in the source code
    - The value of this field must be used to order and group Jobs in the listing page (see also #882)
    - The Job listing page and the REST API should be filterable based on the value of this field
- The JobResult database model must have a ForeignKey to the Job that it corresponds to
    - It *may* be possible to write a database migration to automatically update existing JobResults to set this key appropriately?
    - Regardless, for backwards compatibility, until 2.0 at least, the JobResult model must still retain and populate a `name` field, even though this will become somewhat redundant and should be considered deprecated.
    - Note that not all JobResults correspond to a Job at present, as Git repository synchronization also creates a JobResult. Converting Git repository synchronization to be Job-based may be desirable (see also #275) but doing so is explicitly out-of-scope for this story.
- Similarly, the ScheduledJob model must add a ForeignKey to its corresponding Job, but for backwards compatibility must also retain its `job_class` field for now.
- It must be possible to define object-based permissions to restrict/permit running of specific jobs based on their name, category/grouping, tags, custom fields, etc.
    - It may be that the existing `run_job` permission plus the object-based permissions enabled by implementing the concrete Job model is sufficiently granular to meet this need "for free", but this must be tested.
- It would be highly desirable to add a new `approve_scheduledjob` permission that can be used to control which users are permitted to approve a given ScheduledJob based on its associated Job database record. This may be out of scope for this particular deliverable though.

**Comment by glennmatthews** [comment]
The changes that this will bring to the Jobs REST API require that we decide on an approach for REST API versioning - https://github.com/nautobot/nautobot/issues/1465

**Comment by glennmatthews** [comment]
Closing this as implemented by #1411, #1457, and #1490. REST API versioning is tracked by #1465 and will be implemented under #1521.
