### ISSUE TITLE
Cannot remove device from IP if set as primary

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1053]
### Environment
* Python version: 3.6.8
* Nautobot version: v.1.1.4

I can set primary IP for a device using edit form of the IP, but I cannot undo the step using the same way. The only way to remove primary IP is from device side. Pictures are worth a thousand words:
![image](https://user-images.githubusercontent.com/26114847/140036992-7502b6a5-c382-49e8-ad10-d8086e820acc.png)
-> 
![image](https://user-images.githubusercontent.com/26114847/140037020-46b1a8a8-1b5a-447a-bb0e-1f3687fb2358.png)
-> 
Update
->
![image](https://user-images.githubusercontent.com/26114847/140037066-49c33ce9-047c-4a95-8237-5f1b3ed2e0a4.png)

### Steps to Reproduce
1. create test device
2. create test interface for the device
3. create test IP
4. set the IP as primary for the device on the interface
5. try to undo your last step from IP edit form

### Expected Behavior
device removed from IP

### Observed Behavior
cannot remove device from IP
![image](https://user-images.githubusercontent.com/26114847/140036637-6b78d423-bf82-489b-a665-5f3088fcbfe5.png)

**Comment by jathanism** [comment]
Great catch, thank you. It's aggressively working as intended!!

**Comment by glennmatthews** [comment]
A workaround is to do the operation in two steps - first uncheck "Primary IP" and save the address, then edit it a second time and remove the device/interface assignment.

**Comment by glennmatthews** [comment]
Looks like the relevant code is in `IPAddress.save()` and in `IPAddressForm.save()`. `IPAddressForm.save()` calls `IPAddress.save()` before updating the `primary_ip4` or `primary_ip6` field on the associated device, and `IPAddress.save()` throws the mentioned error message because it is out of sync with the `primary_ip4`/`primary_ip6` field at that point in time.

It **might** be as simple a fix as reversing the order of operations so that the primary flag gets updated before the IPAddress is updated, but that needs to be validated and tested thoroughly.
