### ISSUE TITLE
creating and immediately assigning a value to a custom field gets overwritten by provision_field()

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot#1249]
### Environment
* Python version:
* Nautobot version: 1.2.2

### Steps to Reproduce
1. Run a Job that creates a new `CustomField` record and then assigns values for this field on various objects (`instance.cf["my-custom-field"] = "some-value"`, `instance.cf.validated_save()`)
2. Wait a few seconds after the job completes
3. Inspect objects that were modified by this job

### Expected Behavior

Custom field should have the value assigned by the Job.

### Observed Behavior

Custom field shows default value. Inspecting the changelog history for the object shows the field being set to the correct non-default value, but it gets overwritten (without a corresponding ObjectChange record) by the `provision_field` background task.

I think fixing this might be as simple as changing provision_field() to avoid overwriting any already-set value, e.g.:

```python
        for ct in ContentType.objects.filter(pk__in=content_type_pk_set):
            model = ct.model_class()
            for obj in model.objects.all():
                # WAS ORIGINALLY obj._custom_field_data[field.name] = field.default
                obj._custom_field_data.setdefault(field.name, field.default)
                obj.save()
```

**Comment by glennmatthews** [comment]
I wonder if all three of (`provision_field`, `update_custom_field_choice_data`, and `delete_custom_field_data`) should create ObjectChange entries if they modify an object?

**Comment by Thetacz** [comment]
I think this causes another bug, so writing here instead of new one.

If you create the field and add some values for it, it's serialized json has value for `field` as None. But changelog on creation shows the field `field` populated with ID of the custom field.
![image](https://user-images.githubusercontent.com/26114847/150393505-9391704f-7e5b-4b5a-b200-cfaab471f1ec.png)

Note: querying based on values in the field still works, so this `/api/extras/custom-field-choices/?field=os_owner` shows only choices for `os_owner`.
![image](https://user-images.githubusercontent.com/26114847/150393184-dc3f62c7-f176-457e-b3a4-40ade1470be6.png)
This is an older custom field, the field `field` is serialized correctly here.
![image](https://user-images.githubusercontent.com/26114847/150393272-94536d7a-fe09-4167-97c2-88e4d3cac0f0.png)
