### ISSUE TITLE
UI invalid information displayed when clicking on "Change Log" tab

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#1253]
### Environment
* Python version: 3.9
* Nautobot version: 725013287a8b (v1.2.3)

### Steps to Reproduce
1. Select a "Device Types" entry (https://localhost:8443/dcim/device-types/fe088c13-4f37-42ff-b476-cd9e8c02274b/)
2. click on tab "Change Log"  (https://localhost:8443/dcim/device-types/fe088c13-4f37-42ff-b476-cd9e8c02274b/changelog/)
3. click on Tag "Device Type"  (https://localhost:8443/dcim/device-types/fe088c13-4f37-42ff-b476-cd9e8c02274b/changelog/#tab_main)
3.

### Expected Behavior
The selected info should be displayed.

It seems that the url is not correct (.../changelog/#tab_main instead of '.../')

Same problem when selecting "Advanced" Tab (https://localhost:8443/dcim/device-types/fe088c13-4f37-42ff-b476-cd9e8c02274b/changelog/#tab_advanced)

### Observed Behavior
After clicking the "Change Log" page is sill be displayed

![image](https://user-images.githubusercontent.com/8406301/148767563-8ccd5894-dfe8-4c82-96e1-3e8c4ab76a7c.png)

**Comment by glennmatthews** [comment]
Thanks for the report! I can confirm the issue. From a quick look at the code, it looks like the issue is that `nautobot/dcim/templates/dcim/devicetype.html` has its own custom `block javascript` block, which is replacing rather than augmenting the javascript defined in the base `nautobot/core/templates/generic/object_detail.html` template. Fixing this *should* be as simple as adding a `{{ block.super }}` statement to the javascript block in `devicetype.html` so that it inherits the base javascript as well.
