### ISSUE TITLE
MIssing venv activation step in install guide

### ISSUE THREAD

**Issue by pke11y** [nautobot/nautobot#134]
### Environment
* Python version: 3.8.5
* Nautobot version: 1.0.0b2

### Steps to Reproduce
1. Follow install instructions for venv
2.
3.

### Expected Behavior
```
$ echo $PATH
/opt/nautobot/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

### Observed Behavior
```
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```
Need to activate the venv to view it in the $PATH
```
$ source $NAUTOBOT_ROOT/bin/activate
$ echo $PATH
/opt/nautobot/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

**Comment by pke11y** [comment]
Will put in a PR for it

**Comment by jathanism** [comment]
We don't want to activate. Instead we want to assert that `/opt/nautobot/bin` is in the `$PATH`. On which OS version did you not experience this being added by default?

I'd rather that we just be more explicit about the PATH than restore using activation of the virtualenv, since we're trying to move away from that.

**Comment by pke11y** [comment]
It was on Ubuntu 20.04.

**Comment by jathanism** [comment]
Can you please confirm that you didn't miss this step that has you update and re-read `~/.bashrc`?

https://nautobot.readthedocs.io/en/latest/installation/nautobot/#update-the-nautobot-bashrc

If you did that, in a fresh user session, can you please `sudo -iu nautobot` again and then `echo $PATH` again? This is what it looks like on my test system running Ubuntu 20.04:

```
$ sudo -iu nautobot
nautobot@jathan-nautobot-testing:~$ echo $PATH
/opt/nautobot/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

**Comment by pke11y** [comment]
I'm fairly sure I followed the steps as documented.
Here's the shell history for reference.
```
$ sudo useradd --system --shell /bin/bash --create-home --home-dir /opt/nautobot nautobot
$ sudo -iu nautobot
$ echo "export NAUTOBOT_ROOT=/opt/nautobot" >> ~/.bashrc
$ source ~/.bashrc
$ echo $NAUTOBOT_ROOT
/opt/nautobot
$ python3 -m venv $NAUTOBOT_ROOT
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

Doing as you suggested from a new session worked as documented.
```
$ sudo -iu nautobot
$ echo $PATH
/opt/nautobot/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

**Comment by jathanism** [comment]
Ahhh okay... I see why it's out of phase now. We just revised the docs the other day to streamline creation of the user and the virtualenv.

We were creating the virtualenv prior to sudo to `nautobot` before, which would cause `/opt/nautobot/bin` to be present already. The default `~/.profile` checks for the presence of `$HOME/bin` and automatically prepends `$PATH` with it if that directory is found.

So, need to change the order of things again so that `source ~/.bashrc` comes AFTER creation of the virtualenv.
