### ISSUE TITLE
Interfaces with "/" are automatically sorting first when it should be based on number before "/"

### ISSUE THREAD

**Issue by cabellooa** [nautobot/nautobot#1342]
### Environment
* Python version: 3.8.10
* Nautobot version: 1.2.3

### Steps to Reproduce
1. Adding Arista device type DCS-7280SR-48C6
2. Look how interfaces are sorted

### Expected Behavior

Interfaces should start:

Ethernet1
Ethernet2
...
Ethernet48
Ethernet49/1
Ethernet50/1
...

### Observed Behavior

![image](https://user-images.githubusercontent.com/25310616/152853816-d9707f61-f133-44c8-9edb-437abb1aeca3.png)

**Comment by glennmatthews** [comment]
> ```
> In [5]: for intf in Interface.objects.all():
>    ...:     print(f"Interface.name:{intf.name}, Interface._name:{intf._name}")
>    ...:
> Interface.name:Ethernet49/1, Interface._name:0049999999999999Ethernet000001............
> Interface.name:Ethernet49/2, Interface._name:0049999999999999Ethernet000002............
> Interface.name:Ethernet48, Interface._name:9999999999999999Ethernet000048............
> ```

Based on reviewing [`naturalize_interface`](https://github.com/nautobot/nautobot/blob/develop/nautobot/utilities/ordering.py#L48) this is working as implemented - Ethernet49/1 is interpreted as "slot 49, id 1" while `Ethernet48` is interpreted as "slot N/A (mapped to 9999, i.e. last in the ordering), id 48", hence why all the slotted interfaces are sorted before all the non-slotted interfaces, but ordering is preserved within each group.

It would certainly be possible to change things so that "slot N/A" gets sorted first rather than last, but I'd definitely be concerned as to whether this change would result in another bug being filed down the line complaining that "Ethernet100" gets sorted before "Ethernet 1/1", i.e. asking for the current behavior to be restored.

I'll also note that there is already a lot of previous history in NetBox surrounding interface ordering behavior - as of yet no one there or here has been able to come up with a one-size-fits-all solution to respecting all interface numbering conventions on differing platforms and OSes - this is simply a very difficult problem to solve.

**Comment by joewesch** [comment]
I wonder if `Ethernet48` should instead be "slot 48, id 0" in that case then.

**Comment by itdependsnetworks** [comment]
I had similar concerns. The best I could think of is to provide this as a "pluggable feature", with the ability to send slug to a custom function.

**Comment by jathanism** [comment]
After deliberation we decided the juice is not worth the squeeze to change this at this time. If we were to change the way interface names are sorted (which would be considered a breaking change), or allow for the sorting to be pluggable, it would have to be in Nautobot v2 or later.
