### ISSUE TITLE
custom field Selection value name change causes data inconsistency

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#135]
### Environment
* Python version: 3.6.8
* Nautobot version: v1.0.0b2

Coming from Netbox v2.9.9 (installing through v2.10.3) there is an issue with custom field type Selection. Values of this type no longer have any ID so changing them causes data inconsistency possibility, which becomes reality once object with this assigned custom field is changed. This issue itself is silent, but the data inconsistency results in mess.

Let me explain on example. Let's have a custom field type Selection named `zone_cleanliness` for `ipam.Prefix` model. Set possible choices to `red,green`.
![image](https://user-images.githubusercontent.com/26114847/110826788-ba2a3b80-8295-11eb-8f9b-6b1189571e10.png)
![image](https://user-images.githubusercontent.com/26114847/110826672-9bc44000-8295-11eb-8f8f-ec4a25c2f8ee.png)

Now let's have a new prefix and set the new custom field `zone_cleanliness` to `red`.
![image](https://user-images.githubusercontent.com/26114847/110827130-0d9c8980-8296-11eb-9671-708ecacde80f.png)

Now someone comes and does not like the zones are in lowercase. They are important so sets the to uppercase. This is the trigger to the issue, changing names slightly expecting them to stay.
![image](https://user-images.githubusercontent.com/26114847/110827316-3b81ce00-8296-11eb-9df3-180850afe17d.png)

That triggered the data inconsistency. The `zone_cleanliness` now has 'invalid' choice. Invalid, because it is not defined anywhere and cannot be set.
![image](https://user-images.githubusercontent.com/26114847/110827653-95829380-8296-11eb-9da4-b9409406f2f7.png)
Editing the prefix does only shows the new values for the custom field. The old value is not only not in the selection, but completely gone from the field.
![image](https://user-images.githubusercontent.com/26114847/110827800-b64ae900-8296-11eb-9a27-575ac11ee9f9.png)
If another field if the prefix is edited (via UI), the custom field `zone_cleanliness` is reset to None, effectively resulting in data loss. Example with changing status `active` -> `reserved`, screen of changelog(censored unrelated custom fields):
![image](https://user-images.githubusercontent.com/26114847/110828248-235e7e80-8297-11eb-9473-895bff45a4fd.png)

Note: This happens even if only part of single name is replaced. That name is affected. So for example typos are an issue too.

Why BUG?
1. Coming from Netbox v2.9.9 this is a thing that worked, so regression bug from my point of view.
2. Changing name is something that seems like it should work. But the result is slowly introducing data inconsistencies with potential data loss from the object. (The data stays in the changelog, but is not easily reachable. And the changelog can be deleted before the issue is noticed.)

Possible way to fix this is not having Selection type as list of strings, but list of objects containing `value` (string) and `ID` (or any unchangeable value). And handle the Selection type by `ID` everywhere, but show the `value` to user. Serialized like this:
```
{
    "value": "RED",
    "id": "1d11dbc3-1809-4ec8-8daa-6a3936318772"
}
```

### Steps to Reproduce
1. Create a custom field with type Selection
2. Create some possible choices for the custom field
3. Link the custom field to any model
4. Create new object (or edit existing) with the model
5. Set the new custom field to any choice (just remember which one) for the new object
6. Change name of the assigned choice value
7. Check the created object

### Expected Behavior
Assigned custom field Selection new value replaces the old value everywhere

### Observed Behavior
The value did not change
Editing anything (and not touching the custom field) will erase the value
It is only possible to edit to the new value

**Comment by jathanism** [comment]
@Thetacz Thanks for the detailed bug report! We'll need a little time to triage it but you certainly made it easier on us. :)

**Comment by lampwins** [comment]
Great report! Fundamentally, this is a result of the custom fields overhaul in NetBox v2.10 which subsequently became a part of Nautobot. That being said, this is certainly a bug because even though it is due to deliberate tradeoffs in the design, these data consistency issues are undesirable and we can fix them.

As you point out in NetBox <2.10 choice options were stored in a separate model and custom field value objects used foreign keys to the options, which ensured consistency of the data. In the current design, the value data is stored directly on the end objects via a JSON field. This means however a foreign key is not possible, and thus to simplify matters, the choices definition was collapsed into the custom field model, as a comma-separated value.

My proposal to address this includes moving the choices back to their own model but still storing value data, denormalized, on the actual instances like today. Having a separate model will better allow us to identify the changes to the choices and then update all instances to reflect those changes. As for updating the data upon a change, we actually need to do this in the background due to the time it takes to iterate over all objects. You can see this today in moderately sized data sets when you delete a custom field that is applied to many instances, like interfaces.

This is actually a much larger issue that deals with changes to custom field data in general. There are a handful of individual bugs, including this one, that we have identified recently. Ultimately, we need to address these gaps in the custom fields design methodically and holistically, instead of patching things with continual bandaids.

As we begin to track these other issues, I think it makes sense for us to roll them up under one umbrella GitHub issue for design and tracking discussion. As we do that, we will certainly link this issue there, but we may also close it in the process. I just want to point out that if we do that, we are still working on the bug, just tracking it as a larger effort.
