### ISSUE TITLE
Extend YAML loader to support `!include` constructor

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#1379]
### Environment
* Python version: 3.8
* Nautobot version: 1.2.5

### Proposed Functionality

`YAML` language doesn't support by default referencing/including other definitions from other `YAML` files (similar to `JSON` references). 

It could be an interesting feature to modify the current `load_yaml` [behaviour](https://github.com/nautobot/nautobot/blob/0e491e19d137b41a685c4f97953d2dbe31295862/nautobot/extras/jobs.py#L487) extending the constructor with something like [this](https://gist.github.com/joshbode/569627ced3076931b02f)

### Use Case

The basic use-case is to allow the reusability of `YAML` data in environments where there is an overlapping of definitions with some customizations, for instance in config context schemas.
Specially useful for when using `anchors` that would be reused multiple times.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by glennmatthews** [comment]
Thanks for the feature request. Can you clarify - are you asking for this to be a feature of the Job class's simple `load_yaml` helper method (which you linked to), or a feature of the Git Repository sync logic for handling YAML definitions of config contexts (which you referenced in the use case), or both?

Offhand I'm skeptical about adding support for non-standard YAML language features in Nautobot, but am open to convincing otherwise.

**Comment by chadell** [comment]
My concrete question was for the Git Repository sync, because we identified this on defining config context schemas.

I agree with you that supporting non-standard YAML features is not the "default" choice because of the potential issue and support it could mean, but on the other hand this idea could help a lot to expand the potential of complex `yaml` definitions. Obviously, this should come with proper documentation to make it clear.

The short term alternative is to use `JSON` instead with the feature:
```json
{
    "items": {
        "$ref": "./definitions/ip.json#ipv4_address"
    }
}
```

**Comment by jathanism** [comment]
After deliberation we decided that this is not a good fit for the core, because the side effects could be very dangerous, such as a maliciously crafted `!include` to pull in files outside of a safe or sandboxed environment. If we could perfectly jail it, test it, and document it perhaps, but at this time we think this would introduce more problems than it would solve.

On that note, it does sound like this could be a solution for a project like `netutils` that could be used as a helper, but not part of the core itself.

**Comment by chadell** [comment]
thanks @jathanism  for your feedback!
