### ISSUE TITLE
[UI] VMs and devices in cluster from cluster type view is aways 0

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#1459]
### Environment
* Python version: 3.6.15
* Nautobot version: v1.2.7

Looking at VM and device count from cluster type view always shows 0:
![image](https://user-images.githubusercontent.com/26114847/157234930-905ecb9c-af08-484f-add6-2e9f6a272bd8.png)
![image](https://user-images.githubusercontent.com/26114847/157235367-bc99ab34-54ae-4a7a-b18e-67e2e4993330.png)
Show here on demo instance:
https://demo.nautobot.com/virtualization/cluster-types/test-cluster-type/

### Steps to Reproduce
1. Create cluster type
2. Create cluster
3. Create VM
4. Open created cluster type
5. look at number of VMs in the created cluster from this view
6. look at number of devices in the created cluster from this view

### Expected Behavior
1 (number of VMs in cluster)
1 (number of devices in cluster)

### Observed Behavior
0 (always)
0 (always)

**Comment by glennmatthews** [comment]
Thanks for the report! It looks like a fix similar to https://github.com/netbox-community/netbox/commit/98ff00bc62ea2ee1cdcaa7273cf961e9425c724c should resolve this.

**Comment by ubajze** [comment]
@glennmatthews I was looking at this and I think the problem is elsewhere. We are already using the `annotate` function. I can easily reproduce this on other pages.

Here is an example:
![Screenshot 2022-03-10 at 14 51 47](https://user-images.githubusercontent.com/6861762/157675698-6508bfe9-904f-404e-889b-16b6839560e2.png)
![Screenshot 2022-03-10 at 14 51 59](https://user-images.githubusercontent.com/6861762/157675733-df87c4a1-3b19-4ff9-85e2-b4d988e7cadf.png)

It looks like a caching problem because, after some time, the number is refreshed.

My initial thought was that the problem is because the `queryset` variable is saved in the class object.
```
class DeviceRoleListView(generic.ObjectListView):
    queryset = DeviceRole.objects.annotate(
        device_count=count_related(Device, "device_role"),
        vm_count=count_related(VirtualMachine, "role"),
    )
```

**Comment by glennmatthews** [comment]
@ubajze That seems like a separate issue to me. ClusterTypeView is not using annotations, unless I'm really missing something - https://github.com/nautobot/nautobot/blob/develop/nautobot/virtualization/views.py#L31 - and adding those annotations would be a necessary first step, regardless of caching issues.

**Comment by ubajze** [comment]
@glennmatthews Ohh, you are right. I am sorry. The first image looks similar to that page:
https://demo.nautobot.com/virtualization/clusters/

So, my previous message should be ignored in the context of this issue.

I can open a PR tomorrow with the solution related to this issue.
