### ISSUE TITLE
Dev Environment: Makemigrations Files Fails Linting Tests

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#148]
### Environment
* Python version: Development Environment
* Nautobot version: 1.0.0b2

### Steps to Reproduce
1. Update models that create a migration
2. Run `invoke build`
3. Run `invoke makemigrations`
4. File is created with root:root user account
5. Black is unable to run
6. File does not meet black standards (I know, Django doing it, not the project)

### Expected Behavior

Expected a migration file to pass linting without needing additional steps

### Observed Behavior

Files had to have ownership changed to be able to blacken the file, then needing to black.

**Comment by jathanism** [comment]
Sounds like you might have come across a couple issues here? Item 5 is due to permissions from item 4?

As for the file not passing listing tests, that's expected, but since they are part of the code base we made the decision to have them match our desired style and linting.

**Comment by jedelman8** [comment]
@jvanderaa is this still an issue?

**Comment by glennmatthews** [comment]
I'll just note that in #180 I added an autoformat option to the black task (`invoke black --autoformat`) that makes it straightforward to handle the Black part - but the file ownership is presumably still an issue.

**Comment by jvanderaa** [comment]
Yes, this is. I'm not sure if this is something that we can handle in the tasks.py makemigrations section to automatically change the ownership. This may just be a part of the process of development to make the changes to the file.

**Comment by jvanderaa** [comment]
Possible idea on the black side, let's exclude that from Black formatting. This way whether it is made inside the container or out, that any migrations created would not hurt the CI process.

**Comment by jathanism** [comment]
I don't really have an issue w/ excluding migrations from `black` seeing as the majority of them are automatically generated, but I do have an issue with the motivation for it being that we have two supported development patterns, and one of them isn't playing nicely.

**Comment by glennmatthews** [comment]
As discussed above, this issue describes two distinct problems:

1) Django's autogenerated migration code doesn't comply with Black
2) Files created from within the Docker dev environment (such as generated migrations) appear with the wrong file ownership on the host system.

For item 1, this is an annoyance but easy enough to solve by running Black against the migrations after they are generated. Since we don't have any control over the code generated by Django, the only other option would be to exclude migrations from Black's checking, and after some discussion amongst the core team we don't feel that doing that would be desirable. The benefit of having consistent code style across the entire project, including migrations, outweighs the inconvenience.

For item 2, this is a notable flaw in the current Docker development environment. More discussion amongst the core team revealed that most of the core team are not actually using the Docker development environment but instead a hybrid virtualenv + Docker services environment that's not currently documented as a workflow, but avoids the file permissions issue naturally. I've opened #507 to track the work needed to document this hybrid workflow as the actual, preferred development workflow for Nautobot.

Thank you for opening this issue - it sparked some important conversations!
