### ISSUE TITLE
Improved Developer Documentation

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#1534]
### As ...

Cora - Coder

### I want ...

better developer documentation,

### So that ...

anyone trying to consume internal APIs can understand proper usage, use cases, etc.

### I know this is done when...

There is a developer documentation section in Nautobot RTD.

### Optional - Feature groups this request pertains to.

- Documentation

### TODO

- #367
- #688

**Comment by glennmatthews** [comment]
We do already *have* https://nautobot.readthedocs.io/en/stable/development/, but I agree it needs significant revision and restructuring. 

- The "introduction" document is a bit wide-ranging, and I think a lot of the project governance information (especially around issue intake and such) is a bit out of date already.
- The "getting started" section's information on setting up a dev environment is pretty decent IMO, but see #507 and #1810 for potential improvements
- "Best practices" is a bit of a dumping ground for good ideas - *would love to see this broken up into a set of specific "how to" cookbooks instead*
- "Style guide" includes a number of things that overlap with "best practices", these two should probably be combined into a single bucket of information that then gets refactored into "how to" cookbooks.
- "Extending models" is a good example I think of what a proper "how to" cookbook might look like, at least as a starting point
- "Application registry" is a decent reference but doesn't really provide any insight into "how to" develop stuff. This is the kind of thing that would ideally be replaced by comprehensive auto-generated API documentation, rather than needing to be maintained as a separate documentation file of its own. Same for "User Preferences".
- "Page Templates", "Navigation Menus", "Home Page Panels" are all pretty good examples of the "how to" cookbooks, IMO.

**Comment by lampwins** [comment]
We have made marked improvements and as such I will close this out in favor of individual, targeted stories in the future.
