### ISSUE TITLE
v1.3: JobResult filter form in UI points to wrong endpoint for "job" field.

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#1562]
### Environment
* Python version: 3.9.2
* Nautobot version: 1.3.0-beta.1

### Steps to Reproduce
1. Run some jobs so you have job results
2. Navigate to Job Results list view in UI
3. Click "Job" search field

### Expected Behavior

There should be a drop-down of Job models to use for filtering.

### Observed Behavior
<img width="350" alt="Job_Results_-_Nautobot" src="https://user-images.githubusercontent.com/138052/160671368-af066f78-d11e-4049-b864-d76ef4d65c75.png">

The field is broken. Looks like `JobResultFilterForm.job_model` is pointing to a defunct endpoint (`/api/extras/job-models/`) and needs to be corrected.

**Comment by glennmatthews** [comment]
This will be a little non-trivial to implement since the `api/extras/jobs/` API endpoint is now versioned, and this dropdown should populate based on the 1.3 (non-default) version of the API. Most likely the fix here will be to:

- extend `nautobot.utilities.forms.widgets.APISelect` (and implicitly `APISelectMultiple`) to include an `api_version` optional constructor argument that if set, sets the `data-api-version` attribute on the widget
- extend `nautobot/project-static/js/forms.js` to look for the `data-api-version` attribute on the widget and set the Accept header version appropriately if present
- modify `JobResultFilterForm` so that it creates its `APISelectMultiple` widget with the appropriate `api_version="1.3"` parameter.
- Document this new feature/pattern in comments and the Nautobot developer documentation.

**Comment by bryanculver** [comment]
Closed with #1591
