### ISSUE TITLE
Hadolint fails on Develop branch using invoke tests

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#1685]
### Environment
* Python version: 3.7.3
* Nautobot version: `develop`

### Steps to Reproduce
1. Checkout develop branch on the repository
2. run `invoke build` followed by `invoke tests`

### Expected Behavior
All the tests pass.

### Observed Behavior
```
Running docker-compose command "run --entrypoint 'hadolint docker/Dockerfile' nautobot"
Creating nautobot_nautobot_run ... done
docker/Dockerfile:165 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
docker/Dockerfile:215 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
ERROR: 1
smk4664@stephens-mbp nautobot %
```

**Comment by glennmatthews** [comment]
It looks like hadolint 2.10 is reporting an issue not previously reported by hadolint 2.0 - this has not been failing in CI because our CI action is pinned to hadolint/hadolint-action@1.6.0 which uses hadolint 2.7. (Confusing? Yes.) We need to fix CI at some point so that it's running the intended version of hadolint.
