### ISSUE TITLE
Add MySQL 8.x support

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#17]
### Proposed Functionality
Support MySQL as a backend.  This is in addition to PostgreSQL.

### Use Case
As a user, my company only uses MySQL.  Nautobot needs to support MySQL for me to be able to deploy it.

### Database Changes
TODO

### External Dependencies
TODO

**Comment by blakedot** [comment]
Personally I'd rather see development resources spent on extending core functionality, rather than making the architecture more complicated & force limiting SQL features to those that are supported by both PostgreSQL & MySQL-compatible DBs.

Speaking of which, if you end up having to do that, here's a good comparison of Python database abstractions:  
https://www.gramps-project.org/wiki/index.php/Database_abstraction_layers_comparison

**Comment by xkilian** [comment]
Wasn't the reason for choosing postgresql due to all the builtin features for manipulating IP addresses. I do not see why this is worth reinventing the wheel.

**Comment by jathanism** [comment]
> Personally I'd rather see development resources spent on extending core functionality, vs. making the architecture more complicated, less performant, & force limiting SQL features to those that are supported by both PostgreSQL & MySQL-compatible DBs.
> 
> If you end up having to do that anyway, I hope you're able to choose a good Python database abstraction.
> 
> Personally I've been using MariaDB's Aria engine for several applications & I'm pretty satisfied with it.

These things aren't mutually exclusive, and the idea is trying to make Nautobot more flexible in deployment and not be tightly-coupled to any specific database backend.

If we do this right, adding support for MySQL will be transparent.

**Comment by jathanism** [comment]
> Wasn't the reason for choosing postgresql due to all the builtin features for manipulating IP addresses. Respectfully.

Yes, it comes down to PostgreSQL native `inet` and `cidr` field types. No other database technology has that out of the box, which makes it a quick and easy decision. 

It is possible to do networks more agnostically, and that's what we want to try to achieve, to allow more people the ability to deploy Nautobot without having to deploy PostgreSQL, which for many, is not a supported option.

It's also not as simple as just using containers, because this is also a challenge for many environments, either not having the experience or the authorization to run such deployment patterns in production.

**Comment by blakedot** [comment]
> allow more people the ability to deploy Nautobot without having to deploy PostgreSQL, which for many, is not a supported option.

if the goal is to support something "self-contained" then perhaps dqlite (distributed SQLite) is worth a look:  https://dqlite.io/

**Comment by jathanism** [comment]
What's left:

- [ ] Documentation on how to install/deploy w/ MySQL
- [ ] Fix lingering bugs in unit tests

**Comment by blakedot** [comment]
> > Wasn't the reason for choosing postgresql due to all the builtin features for manipulating IP addresses. Respectfully.
> 
> Yes, it comes down to PostgreSQL native `inet` and `cidr` field types. No other database technology has that out of the box, which makes it a quick and easy decision.
> 
> It is possible to do networks more agnostically, and that's what we want to try to achieve, to allow more people the ability to deploy Nautobot without having to deploy PostgreSQL, which for many, is not a supported option.

MariaDB has some good docs on their "ip range" tables, as well as performance notes & a reference implementation (e.g. CIDR needs to be converted to "ip ranges" first, etc.), 

https://mariadb.com/kb/en/ip-range-table-performance/#reference-implementation-of-ipv4
HtH

**Comment by jedelman8** [comment]
Addressed by #584
