### ISSUE TITLE
Implement automated UI integration test suite

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#183]
### Proposed Changes

We need to implement automated UI integration testing a la Selenium or Cypress. 

### Justification

The unit test suite is not sufficient nor appropriate for end-to-end user testing of the web application. There are many flows and edge cases unique to certain views or model relationships that are not correctly exercised or tested from this perspective. We need dedicated integration tests for the web UI.

**Comment by jedelman8** [comment]
We should be able to get this started in 1.1.0.  At a minimum, getting the framework in place and a few tests created.  From there, we can continue to add more.

**Comment by glennmatthews** [comment]
Example issue not caught by the existing UT, that would have been caught by adequate UI testing: https://github.com/nautobot/nautobot/pull/179#pullrequestreview-618737118 - a change to the way form fields are rendered to the UI was not caught because the backend validation of the form fields didn't change, and so the fact that the UI and the backend became out of sync was not tested or caught by automation.

**Comment by jathanism** [comment]
Baseline tests: 
- Load home page
- Login
- Click "add site", fill in required fields and create a site object
- Confirm creation of site object
