### ISSUE TITLE
Custom Fields cannot filter by name for content_types

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#201]
### Environment
* Python version: Python 3.8
* Nautobot version: 1.0.0.b2

### Steps to Reproduce
1. Attempt to filter `extras/custom-fields` by `content_types=dcim.device` it fails with **Observed Behavior** below.
2. Attempt to filter `extras/statuses` by `content_types=dcim.device` and it works

### Expected Behavior
Filter custom fields for any that are tied to `dcim.device`

Also, should content-types providers an integer instead of UUID. Not sure if this is due to it being a Django construct primarily.

@jmcgill298 @jvanderaa 

### Observed Behavior
```
{
  "content_types": [
    "“dcim.device” is not a valid value."
  ]
}
```

**Comment by jathanism** [comment]
Thanks @FragmentedPacket for the report. 

We won't be able to solve for integer PKs for content types because they are built-in, but we can at least hide them. We just need to revise the custom fields relationship to use the same content-types related field subclass we added to support a cleaner UX for working with statuses.
