### ISSUE TITLE
Job Results "Filter" only filters per "level", and returns a HTTP 405 error

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#2085]
### Environment
* Python version: N/A
* Nautobot version: 1.3.8 

### Steps to Reproduce
1. Open a Job Results
2. I write something on the "Filter" box
3. The filter applies to only the "level", and not to the "Message
4. if I hit enter, in the "Filter" box, I got a HTTP ERROR 405

### Expected Behavior

First, I would expect that the "Filter" will match the "Message", or if it's only for the "Level" to be explicit on that. Also, it's not accepting case-sensitive, I guess because it's matching not the rendered label, but the actual value of the choice.
I would expect also that when the "Filter" doesn't match anything, anything is rendered.
And, if I hit enter, it should not break, simply ignore it

### Observed Behavior

* Filtering only applies to "Level", not to "Message", and it's not matching the Level label text (non case-sensitive)
* when the filter doesn't match anything, it renders everything, what it is counterintuitive to me.
* If you hit "enter" in the Filter box, it returns a HTTP ERROR 405

**Comment by jathanism** [comment]
For the filtering, this is due to the filtering only being done on the `data-name` attribute of the enclosing `<tr>` element: 

https://github.com/nautobot/nautobot/blob/9a4a2df92cfabcd1a9db35f6f436b907f5fc28e0/nautobot/project-static/js/log_level_filtering.js#L6

For non-matching filter, again a simple flaw in the regex parsing for the input pattern:

https://github.com/nautobot/nautobot/blob/9a4a2df92cfabcd1a9db35f6f436b907f5fc28e0/nautobot/project-static/js/log_level_filtering.js#L7-L10

For hitting enter: The default action for that keydown event needs to be blocked (likely using `.preventDefault()` in JS).
