### ISSUE TITLE
[1.4] Job.run - self.request is None

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#2192]
### Environment
* Python version:      3.9
* Nautobot version:  e02bb08e6c2a (v1.4.0rc1)

### Steps to Reproduce
1. Run a job
2. Log `self.request`
3.

### Expected Behavior
`self.request is not None`

```
import pprint

class MyJob(Job):
    def run(self, data, commit=False):
        self.log_info(self.request, pprint.pformat(self.request, indent=4))
        ...
```
![image](https://user-images.githubusercontent.com/8406301/184311556-d652fac5-3a31-497b-b83c-e48e5f5e07c6.png)

### Observed Behavior
`self.request is None`

**Comment by smk4664** [comment]
I too am getting this issue, I am not sure if it is a regression in 1.4 or not.

**Comment by glennmatthews** [comment]
Thanks for the report! Looks like the code to set this property was removed in #2035. Although we're trying to get away in general from tightly coupling Jobs to HTTP requests (due to the introduction of features like JobHooks), `self.request` is a documented feature of Jobs (https://nautobot.readthedocs.io/en/stable/additional-features/jobs/#accessing-request-data) so we shouldn't have removed this feature. We'll get this fixed.

**Comment by jifox** [comment]
What is the suggested way of logging the caller (username and ip) without accessing self.request?

This is the only reason why I am using it

**Comment by smk4664** [comment]
Here is my usecase for `self.request`:
I am working on creating a job to sync a git repository, I noticed that `nautobot.extras.datasources.git.pull_git_repository_and_refresh_data` did not use request and just passed it to `refresh_datasource_content` which doesn’t seem to require request, so I was thinking that maybe I could get away without passing in request.  When I run the job though, `pull_git_repository_and_refresh_data` is calling `refresh_datasource_content` by passing positional args, if request=None  it didn’t properly pass the request=None object. It seems as though it passes job_result to the request parameter.  So the sync would never happen. I added `job.request = request` back to job.py, and the sync worked. I am thinking that if the refactor of moving away from request objects was also done to GitRepository with 1.4, I would not have the need for a job to have `self.request`. 

Even if `refresh_datasource_content` was changed to accept `User` instead of `request`, I would still  have the issue of requiring the user that triggered the `Job`.

**Comment by gsnider2195** [comment]
@smk4664 can you post an example of what you were doing in your job that wasn't working so I can make sure it's captured in our unit tests? Was it something like this?

```py
git_repo = GitRepository.objects.get(slug="nautobot")
enqueue_pull_git_repository_and_refresh_data(repository=git_repo, request=None)
```

**Comment by smk4664** [comment]
@gsnider2195 Close,
```
from nautobot.extras.models import GitRepository
from nautobot.extras.datasources.git import pull_git_repository_and_refresh_data
from nautobot.extras.jobs import *


class SyncRepo(Job):

    class Meta:
        name = "Synchronize Repo"
        description = "Synchronize a repo."

    repository = ObjectVar(
        model=GitRepository,
        required=False
    )

    def run(self, data, commit):
        pull_git_repository_and_refresh_data(data["repository"].pk, self.request, self.job_result.pk)
```

**Comment by smk4664** [comment]
I used `pull_git_repository_and_refresh_data` itself so that I could get the logs from the git_sync into my job, instead of creating a second separate job.

**Comment by gsnider2195** [comment]
@smk4664 
I'm not able to replicate that problem on `v1.4.0b1` 

Using your code above I'm able to get the repo to resync even when `self.request = None` as seen here:

```py
class TestPullGitRepository(Job):
    class Meta:
        name = "Synchronize Repo"
        description = "Synchronize a repo."

    repository = ObjectVar(model=GitRepository, required=False)

    def run(self, data, commit):
        self.log_info(f"self.request is {self.request}")
        pull_git_repository_and_refresh_data(data["repository"].pk, self.request, self.job_result.pk)
```

![image](https://user-images.githubusercontent.com/75227981/184666038-e51167a2-c228-45a4-ac71-4d2bd181aadb.png)

If a request isn't provided to `pull_git_repository_and_refresh_data()` I get this error message:

```py
    def run(self, data, commit):
        self.log_info(f"self.request is {self.request}")
        pull_git_repository_and_refresh_data(data["repository"].pk, self.job_result.pk)
```

![image](https://user-images.githubusercontent.com/75227981/184666601-5ee7a5f0-587b-4377-b36e-464dd50c7b52.png)

Were you able to verify that `pull_git_repository_and_refresh_data` was sending the `job_result` as the 3rd positional arg to `refresh_datasource_content()`?
