### ISSUE TITLE
Graphql custom field filter query does not work

### ISSUE THREAD

**Issue by schreyack** [nautobot/nautobot#232]
### Environment
* Python version: Sandbox
* Nautobot version: Sandbox

### Steps to Reproduce
1. Create a custom field and add some data to one object.
2.  Create a query in graphql to filter on that custom field
```
{
  devices {
    name
    custom_field_data(cf_test:"blah")
  }
}
```

### Expected Behavior
Should filter on the data.

### Observed Behavior
Returns an error

```
{
  "errors": [
    {
      "message": "Unknown argument \"cf_test\" on field \"custom_field_data\" of type \"DeviceType\".",
      "locations": [
        {
          "line": 4,
          "column": 23
        }
      ]
    }
  ]
}
```

**Comment by jathanism** [comment]
While I think the correct query would be this...

```graphql
{
  devices(cf_test: "blah") {
    name
    custom_field_data
  }
}
```

... That still doesn't work.

The custom field is not showing in the schema as `DeviceType`. I think we fixed some of this in beta2 and more fixes are in beta3. I tested and while the custom fields DO show in the schema as `DeviceType.cf_test`, filtering still does not work.

I would reckon that custom field filtering may not work anywhere since they are all using the same underlying schema generators.

**Comment by lampwins** [comment]
Would be good to have @dgarros chime in here, but I think something broke recently because there is code that appears to be handling the schema generation for custom fields. Similar code is there for relationships and they appear to be working.

Additionally, the current documentation says this should work and it doesn't:
```graphql
{
  devices {
    name
    cf_test
  }
}
```

**Comment by jathanism** [comment]
> Would be good to have @dgarros chime in here, but I think something broke recently because there is code that appears to be handling the schema generation for custom fields. Similar code is there for relationships and they appear to be working.
> 
> Additionally, the current documentation says this should work and it doesn't:
> 
> ```graphql
> {
>   devices {
>     name
>     cf_test
>   }
> }
> ```

There is code to handle the filtering but there's been a few filter-related issues that appear to be centering around the same underlying issue: Mapping non-concrete database fields (whether they be computed model fields like `IPAddress.address` or filterset fields like `nautobot.dcim.filters.DeviceFilterSet.has_primary_ip`).

Related: #167, #233, #225
