### ISSUE TITLE
GraphQL boolean filters are borked

### ISSUE THREAD

**Issue by dgjustice** [nautobot/nautobot#233]
### Environment
* Python version: 3
* Nautobot version: develop

### Steps to Reproduce
1. 
```json
{
  devices(has_primary_ip:"False") {
    name
  }
}
```
2. 
```json
{
  "errors": [
    {
      "message": "unhashable type: 'list'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "devices"
      ]
    }
  ],
  "data": {
    "devices": null
  }
}```

### Expected Behavior
A list of devices

### Observed Behavior
An error

**Comment by jathanism** [comment]
There is currently a known issue we are working on reflecting 100% of filtering or lookup using virtual fields. In this context a virtual field is any non-concrete database field, whether that is a computed model field (such as `IPAddress.address` or a filter field such as `Device.has_primary_ip`.

We have a pending fix to address this for `IPAddress.address` and also fix filtering on method-based filter fields (which most virtual filter fields are), but it's not comprehensive enough to address the root cause here.

Reference: https://github.com/nautobot/nautobot/pull/225

In any case, thanks for the report, since it's highlighting that this is a bigger issue.
