### ISSUE TITLE
Cannot trigger Job with FileVar arg through request

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#2473]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.1
* Python version: 3.10.6
* Database platform, version: PostgreSQL
* Middleware(s):

### Steps to Reproduce
1. Create Job with arg of type `nautobot.extras.jobs.FileVar` named `data_file_param`
2. Trigger the job with cURL / Python requests, try to send file `data.json` with simple JSON data inside
```
import requests

url = "https://IPPLAN_URL/api/extras/jobs/plugins/PLUGIN_NAME/JOB_NAME/run/"
token = "USER_TOKEN"

data = {
        "commit": True,
        "dry_run": False,
        "memory_profiling": True,
        "delete_confirmed": False,
}
headers = {
    "Authorization": f"Token {token}",
}
r = requests.post(
    url=url,
    files={"data_file_param": open("data.json", "rb")},
    data=data,
    headers=headers
)
```
content of `data.json`: 
```
{'test': 'ok'}
```

### Expected Behavior
Job triggered, file available in data (same as through UI)

### Observed Behavior
file missing in data:

 `{"errors":{"data_file_param":["This field is required."]}}` if the arg is required

The job will start if the arg is optional, but errors out with:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/jobs.py", line 1119, in run_job
    file_ids = [data[f] for f in file_fields]
  File "/usr/local/lib/python3.10/site-packages/nautobot/extras/jobs.py", line 1119, in 
    file_ids = [data[f] for f in file_fields]
KeyError: 'data_file_param'
```

### Note
Sending decoded JSON in the request data results in `{"errors":["{'test': 'ok'}" is not a valid UUID."]}`
```
data = {"commit": True,
        "data": {
            "dry_run": False,
            "memory_profiling": True,
            "delete_confirmed": False,
            "data_file_param": json.load(open("data.json", "rb")),
        }
}
headers = {
    "Content-Type": 'application/json',
    "Authorization": f"Token {token}",
}
requests.post(url=url,json=data, headers=headers)
```
But the correct way of uploading file should be to use `Content-type=multipart/form-data`, which I used in the reproducer. It is even in the Django widget code for `FileInput`: https://github.com/django/django/blob/37a13cc92d51d5a57b42240b9a5dd250648efa24/django/forms/widgets.py#L417

**Comment by bryanculver** [comment]
So thoughts on how we go about handling the input data for this situation...

Multipart forms don't allow nesting, so our existing API schema won't work: `data` and `schedule` are nested dictionaries so sending payloads like this:

```python
job_data = {
  "var1": True,
  "var2": "A String",
  "var3": {"name": "role"},
}

api_payload_data = {
  "commit": True,
  "data": job_data,
  "schedule": {
    "name": "Testing",
    #....
  }
}
```
won't work with `Content-type=multipart/form-data`.

Some potential options:

**Require nested dictionaries (mainly `data` and `schedule`) to be pre-converted to JSON strings that we can deserialize on the receiving side.**

Because of the way multipart/form-data works it would split each key out into it's own part. JSON dump/loading for these data structures should be straightforward.

_So:_

```python
job_data = {
  "var1": True,
  "var2": "A String",
  "var3": {"name": "role"},
}

schedule_data = {
  "name": "Testing",
  #....
}

api_payload_data = {
  "commit": True,
  "data": json.dumps(job_data),
  "schedule": json.dumps(schedule_data)
}
```

**Require Job execution API spec to more closely match what our UI payload looks like.**

This changes the spec but could make API and UI tests identical. Can split the schema detection based on incoming content type (multipart being new taking on the new form) before making a breaking change. 

_So:_

```python
api_payload_data = {
  "_commit": True,
  "var1": True,
  "var2": "A String",
  "var3": {"name": "role"},
  "_schedule_name": "Testing",
  #...
}
```


**Require files to be "serialized" via something like Base64 encoding**

To be honest I like this option the least because it wouldn't use any of the built-in Django file handling and we may run into weird behaviors with file size & payload limits.

_Something like:_

```python
api_payload_data = {
  "commit": True,
  "data": {
    "var1": True,
    "var2": "A String",
    "filevar_name": "data.json",
    "filevar_contentype: "text",
    "filevar_contents: open("data.json", "rb")),
  }
}
```

**Comment by glennmatthews** [comment]
Personally I don't like the idea of mixing JSON strings into a multipart/form-data payload (option 1). I think option 2 (take inspiration from the UI form data) seems more sensible.
