### ISSUE TITLE
Git `provided_contents` not honored for Jobs when refreshing repo

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#2601]
### Environment
* Nautobot version (Docker tag too if applicable): 1.4.5
* Python version: 3.10
* Database platform, version: pgsql
* Middleware(s):

### Steps to Reproduce
1. Create a repo which hosts valid jobs, but do not select `jobs` in "Provides"
2. Save & sync

### Expected Behavior
Jobs are not installed (or removed if previously selected in provides)

### Observed Behavior
Jobs are installed

### Additional informations

The missing condition, like in `_get_job_source_paths`, seems to be in [`refresh_git_jobs`](https://github.dev/nautobot/nautobot/blob/v1.4.5/nautobot/extras/datasources/git.py#L913)

**Comment by glennmatthews** [comment]
Thanks for the report!

I must be missing some nuance of the code, because this *should* be working correctly with the [`if not delete:` check](https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/datasources/git.py#L916) preventing the jobs from being loaded (refreshing a repo without the appropriate "provides" flag set will call the refresh function with `delete=True`).

**Comment by glennmatthews** [comment]
You're right, my mistake. I was thinking of the [`if "extras.configcontextschema" in repository_record.provided_contents and not delete:` pattern](https://github.com/nautobot/nautobot/blob/v1.4.5/nautobot/extras/datasources/git.py#L762), and as you noted the Job case is missing a `if "extras.job" in repository_record.provided_contents` check.
