### ISSUE TITLE
Jobs Overhaul: Jobs should no longer wrap in atomic, leave to author

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#2726]
As opposed to #1991, we should remove all atomic "magic" behavior and leave it to the Job author.

This allows authors to decide where and when they want certain database calls to be atomic. Since more and more jobs are interacting with other systems, wrapping the entire job in `with transaction.atomic:` causes data inconsistencies: Nautobot can roll back its database changes but API calls to other systems that may have created data.

Remove the testing specific workaround and any tests related to the atomic block functionality.

**Comment by lampwins** [comment]
Need good documentation on migration path for this.

**Comment by gsnider2195** [comment]
Do we want to continue to provide the `commit` argument from core or leave that up to the job author to implement as well?

**Comment by gsnider2195** [comment]
Decided to remove `commit` argument

**Comment by gsnider2195** [comment]
What's the plan for `dry-run` and scheduled job approval? If a job requires approval but dry-run is set the job can be run without approval. Does that feature get dropped as part of this issue or does the commit flag need to remain to support this?

**Comment by bryanculver** [comment]
I think `dry-run` needs to be dropped as well because AFAIK that's being done via aborting the transaction (as in commit=False).

Job approval would stay though. This would provide greater weight to the job approval process: ensuring the job has a dry-run option it builds if necessary or preventing accidental non-dry-runs.

**Comment by lampwins** [comment]
Thinking about this... I feel we should maintain the `dry-run` primitive as an interface, but provide no implementation by default. In essence this is the same as ansible's `--check` in that Job authors ("modules" in ansible speak) must implement support for `dry-run` in their job but doing so will enable a standard and consistent UX because this is a common use case and is expected in an automation platform. I see us implementing another `Meta` flag like `provides_dry_run = True` and we would use that in the UI and the approval/schedule flow to allow the relevant functionality.

So the onus is still on the Job author, but we provide the standard interface pattern. The Job author could then rely on a standard `dry_run` input and they can chose what to do with that in their code.

**Comment by bryanculver** [comment]
Closed as was done by not implementing in #3483
