### ISSUE TITLE
Document manual update path between v1.0.0b2 and v1.0.0b3

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#284]
### Environment
* Python version: 3.9
* Nautobot version: v1.0.0b2/ v1.0.0b3

### Proposed Functionality

Enhance the documentation to manually transfer data between the different versions

### Use Case
We have already a large database, and would like to update - 
as the release notes say, a new database must be created.

However, since I could migrate data from netbox to nautobot,
there also should be a way to get the data migrated, maybe with an export and import?

This should be documented, if possible.
If not, a tool should exist to faciliate this.

**Comment by glennmatthews** [comment]
Hi, thanks for opening this issue. We apologize for the trouble, but there’s currently no supported data migration path from 1.0.0b2 and earlier to 1.0.0b3 and later, due to numerous data model changes made in 1.0.0b3. (I’ll note that this *will* be the last set of breaking data model changes prior to 1.0.0 - migrating from 1.0.0b3 to 1.0.0, when released, should be relatively painless as an in-place upgrade, and any official releases (non-beta) after 1.0.0 will follow semantic versioning and make every effort to support appropriate data migrations.)

While it would be theoretically possible to develop a migration application (similar to nautobot-netbox-importer) it would take a significant amount of development effort to implement, and so we’re unlikely to be able to commit the required resources to doing so.

If I may ask, what is the source of the data in your current Nautobot database? If it was populated from a prior NetBox instance, your best bet will almost certainly be to use the latest version of nautobot-netbox-importer to do a fresh import from NetBox into a fresh installation of Nautobot 1.0.0b3.

**Comment by sirtux** [comment]
Well,
the data came from netbox initially, and then scripts did their things, and I now have more than 10k devices with network etc in the system, as I didn't expect such a hard breaking and GraphQL was it worth to move to nautobot...

What would happen, if I get the data with "nautobot-server dumpdata" and import it in the new instance with "nautobot-server loaddata"? 

Are the model changes only db related, or also the representation of the models in JSON?

**Comment by jathanism** [comment]
> Well,
> the data came from netbox initially, and then scripts did their things, and I now have more than 10k devices with network etc in the system, as I didn't expect such a hard breaking and GraphQL was it worth to move to nautobot...
> 
> What would happen, if I get the data with "nautobot-server dumpdata" and import it in the new instance with "nautobot-server loaddata"?

It's a rabbit hole. See below:

> 
> Are the model changes only db related, or also the representation of the models in JSON?

Short answer is it's both. The changes are db-related but they also affects the representation of the models in JSON  because particularly the network fields were changed pretty significantly (for example `IPAddress.address` is now a virtual field backed up by three concrete fields). We also replaced the user model, so any object that has a relationship to users introduces a cascading issue with interdependencies in cross-table relationships. 

We recently expanded the migration guide to cover the data model changes: https://nautobot.readthedocs.io/en/latest/installation/migrating-from-netbox/#data-model-changes

I understand that it is frustrating, but because of the intertwined nature of the objects and the schema changes, we had to make a difficult call between supporting a direct upgrade from beta2 to beta3 or pushing the releases back even further to attempt to create clean schema and data migrations.

After attempts to do so, we deemed that it was not worth the heartache to try to do it, and so the outcome was to just "reset" from beta3 onward. As @glennmatthews indicated, the bold and invasive schema changes are done and we will not be doing the again from here on out. We had to make the tough call to do it BEFORE the 1.0.0 release, so that we didn't have people migrating to Nautobot only to have to worry about another set of complicated database changes after the stable launch.

**Comment by sirtux** [comment]
Okay,

I understand this, and no hard feelings.

But if I see right, getting an object via REST-API and adding it to another instance should work, if I copy element by element and make sure the dependecies are met?

If so, I'll write a small script to do that, and add it to this ticket, and then this can be closed.

**Comment by sirtux** [comment]
Okay,

I'll have transferred dcim, tenancy and extra-data via dumpdata and loaddata,
and for IPAM I used the following hacky script:

https://gist.github.com/sirtux/bf0f4189bc2af20041be62a292ad015b

So I'll close this issue, and hopefully no one else will fall over this, or if he does find that script handy.
