### ISSUE TITLE
Implement `django-natural-keys` as base for `BaseModel`

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#2900]
### Proposed Changes

Base models should inherit from [`django-natural-keys`](https://github.com/wq/django-natural-keys) base `NaturalKeyModel` and use `NaturalKeyModelManager` so that…

- `natural_key()` is automatically provided using the uniqueness constraints
    - Currently for each model, we must define `natural_key()` method 
- `Foo.objects.get_by_natural_key()` is also automatically provided, reducing boilerplate
    - Currently for each model, we must subclass `RestrictedQuerySet` in order to publish a `get_by_natural_key()` method
    - And then set `objects = FooRestrictedQuerySet.as_manager()` on the model
- Each model will also receive a `natural_key_slug` that is *immutable* derived from the natural key fields for that object. This can be used in URL fragments in the  "natural key or PK" pattern we have begun to adopt for filters. 

### Justification

We have decided to align around natural keys. We need less boilerplate, not more. In the common case, this should work automatically and result in objects having deterministic uniqueness/natural key constraints with minimal effort. For the uncommon/edge case, we will need to adapt and revise the pattern.

**Comment by bryanculver** [comment]
https://github.com/nautobot/nautobot/pull/2692

**Comment by glennmatthews** [comment]
Since `django-natural-keys` provides a minimal/naive `natural_key_slug` implementation (for one, it doesn't account for the possibility that any of the key components may contain a `-` character), we probably need to come up with our own design here. Since one of the main uses of natural-key-slugs may be in URL patterns, we need something that's URL-safe - therefore I'm proposing that we consider either [percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding) or [punycode](https://en.wikipedia.org/wiki/Punycode) as a starting point.

**Comment by bryanculver** [comment]
Completed with #3423
