### ISSUE TITLE
Incorrect version reported by nautobot-server

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#291]
### Environment
* Python version: 3.6.13
* Nautobot version: 1.0.0b3

`nautobot-server version` returns an incorrect version number while `nautobot-server --version` is correct.
### Steps to Reproduce
1. run `nautobot-server version`

### Expected Behavior

Should returned `1.0.0b3`

### Observed Behavior

```shell
$ nautobot-server version
3.1.8
$ nautobot-server --version
1.0.0b3
```

**Comment by glennmatthews** [comment]
Looks to be reporting the Django version.

**Comment by jathanism** [comment]
> Looks to be reporting the Django version.

Correct. The `version` command is built into Django and displays the Django version. I'll agree this is confusing, especially since the inclusion of the `version` sub-command isn't even documented and appears to be hard-coded because doesn't show when you run `nautobot-server help`.

https://github.com/django/django/blob/3.1.7/django/core/management/__init__.py#L390-L391

**Comment by jathanism** [comment]
Anyhow, confusing as it may be, there's not an easy way to fix this because it's hard-coded in the Django core management code. We'd have to overload everything just to patch this one thing.
