### ISSUE TITLE
1.5.2: ImportError: cannot import name 'CustomFieldModelSerializer' from 'nautobot.extras.api.serializers'

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#2923]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.2
* Python version: 3.8
* Database platform, version: Postgres, inv tasks
* Middleware(s):

### Steps to Reproduce
1. Change tasks.py on nautobot-plugin-device-lifecycle-mgmt to 1.5.2 install
2. Run `inv build`
3. Run `inv debug`

### Expected Behavior

Successful start

### Observed Behavior

```
ImportError: cannot import name 'CustomFieldModelSerializer' from 'nautobot.extras.api.serializers' (/usr/local/lib/python3.8/site-packages/nautobot/extras/api/serializers.py)
```

Appears to be related to #2779

**Comment by bryanculver** [comment]
This is because `nautobot.extras.api.serializers` is not the source of `CustomFieldModelSerializer`. It's inadvertently "re-exported" there because that file uses it internally. Instead that should have been imported from `nautobot.extras.api.customfields`.

Eventually this should migrate to `nautobot.apps.api.CustomFieldModelSerializerMixin`.

**Comment by bryanculver** [comment]
Related: https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/issues/122

**Comment by jvanderaa** [comment]
Closing in favor of related issue.
