### ISSUE TITLE
Support GitHub App authentication

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot#3151]
### As ...

Patti - Platform Admin

### I want ...

to support [GitHub Apps authentication](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps)

### So that ...

more secure authentication (with expiration) for server-to-server calls can be used between Nautobot and GitHub
Today, only personal token is supported: https://docs.nautobot.com/projects/core/en/stable/models/extras/gitrepository/#repository-configuration

### I know this is done when...

I can use a secret group that provides the required GitHub App authentication

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [X] Plugins (and other Extensibility)
- [X] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by bryanculver** [comment]
Can you provide a workflow example where a GitHub App performs `git` operations against a repo? As I read their App documentation it would appear we would be required to implement the API functions of their integration, not `git`. Integrating Nautbot as a GitHub app is entirely it's own thing.

Also would this be better suited as a https://github.com/nautobot/nautobot-plugin-secrets-providers feature?

**Comment by bryanculver** [comment]
@chadell ☝️

**Comment by chadell** [comment]
My idea is, when integrating Nautobot with Git Repositories to allow a new authenticated method. So:

1. Create a GitHub App integration for Nautobot -> it generates a PEM private key
2. Use this PEM key to sign a JWT token to validate the identity
3. This JWT token would be used to interact with GitHub API https://docs.github.com/en/rest/git?apiVersion=2022-11-28#git-data

The PEM key would be a secret to store in some Nautobot secrets provider, similar to the current approach. 
It seems better for server-to-server, instead of creating a Nautobot Github USER account.

**Comment by jathanism** [comment]
The problem we are faced with is we're using the [`GitPython`](https://gitpython.readthedocs.io/en/stable/) library which only supports SSH or HTTPS for interacting with Git repositories. It's not clear to me how Git clone/pull would be done over the GitHub API. The GitHub App authentication as far as I can tell appears to be for using the REST API.

If this PEM is possible to use as a private key bundle, that's a start, but the problem also is that it would require that the key be stored on disk and not in a vault so that the underlying SSH commands on the system are aware of it. This is obviously not what we want, so we'd have to think of some other way.

See: https://gitpython.readthedocs.io/en/stable/tutorial.html#handling-remotes

Unless I'm missing details, out of date, or just wrong (I'm wrong a lot), I don't think this is going to be easily accomplished.
