### ISSUE TITLE
Filter on custom field (selection) can't be changed once filter is configured

### ISSUE THREAD

**Issue by phoenixswiss** [nautobot/nautobot#3196]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.9
* Python version: 3.8.10
* Database platform, version: postgresql, Ubuntu 12.12-0ubuntu0.20.04.1
* Middleware(s): -

### Steps to Reproduce
1. Create a custom selection field and assign it to the object interface with at least two options (optionA, optionB)
2. Configure/select different options on the newly created custom field on some interfaces
3. On the interfaces page, go to the filter input and select optionA from the drop down box and click Apply
4. Change the filter and select optionB instead of optionA and click Apply again

### Expected Behavior
The filter will be modified and all interfaces with optionB defined will be displayed.

### Observed Behavior
The filter will not be changed and interfaces with optionA will be displayed even optionB is selected in the filter window.

**Comment by glennmatthews** [comment]
Appears to be the case for all custom field filtering, not just selection-type custom fields. Reproduced on demo.nautobot.com:

1. go to https://demo.nautobot.com/dcim/interfaces
2. Click the "Filter" button; in the standard filter form (not "advanced") enter `leaf` for the `Role` custom field and click Apply.
3. Page refreshes as https://demo.nautobot.com/dcim/interfaces/?&enabled=&mgmt_only=&mac_address=&nautobot_bgp_models_interfaces_bgp_routing_instance=&cf_role=leaf&q= (note `cf_role=leaf`)
4. Click the "Filter" button, enter `peer` for the `Role` custom field, and Apply.
5. Page refreshes as https://demo.nautobot.com/dcim/interfaces/?&enabled=&mgmt_only=&mac_address=&nautobot_bgp_models_interfaces_bgp_routing_instance=&cf_role=peer&cf_role=leaf&q=  (note `cf_role=peer&cf_role=leaf` instead of the intended `cf_role=peer`. Since `cf_role` is not a multi-value filter, the last-specified value of the query parameter (`leaf`) wins out.

**Comment by glennmatthews** [comment]
Advanced filtering of custom fields appears to be even more broken:

![image](https://user-images.githubusercontent.com/5603551/215803744-670a0ba4-959e-4197-8739-2f65b0eb7f80.png)

results in the query:

https://demo.nautobot.com/dcim/interfaces/?&enabled=&mgmt_only=&mac_address=&nautobot_bgp_models_interfaces_bgp_routing_instance=&cf_role=&undefined=leaf&q=

(note `cf_role=&undefined=leaf`)

![image](https://user-images.githubusercontent.com/5603551/215803975-6bed0d2d-a90d-4bbb-b70e-36df901a86ca.png)

**Comment by gsnider2195** [comment]
Not sure if this is the same issue but I'm seeing the same for the `Interface.mode` filter

![image](https://user-images.githubusercontent.com/75227981/216360978-e1e888b3-03fb-453a-8ec0-ab50a97b8814.png)

https://demo.nautobot.com/dcim/interfaces/?&enabled=&mgmt_only=&mac_address=&nautobot_bgp_models_interfaces_bgp_routing_instance=&cf_role=&undefined=access&q=

(`undefined=access`)
