### ISSUE TITLE
Error when saving dynamic groups is not displayed intuitively.

### ISSUE THREAD

**Issue by ebusto** [nautobot/nautobot#3212]
### Environment
* Nautobot version: 1.5.9
* Python version: 3.10
* Database platform, version: PostgreSQL 14
* Middleware(s): N/A

### Steps to Reproduce
1. Create a parent dynamic group with a child and a filter.

### Expected Behavior
As this isn't allowed, the error should be displayed after attempting to save the new dynamic group: "A parent group may have either a filter or child groups, but not both. Clear the parent filter and try again."

### Observed Behavior
The error is lost, and instead "A parent group may have either a filter or child groups, but not both. Clear the parent filter and try again." is the only visible error message.

**Comment by jathanism** [comment]
Hmm... Are you trying to do this in the UI? And I'm confused a bit, as you seem to be indicating that the expected and observed behavior are the same? Did you copy/paste the wrong error in one of the cases? Thanks in advance!

**Comment by jathanism** [comment]
I went to reproduce and created an initial group called "child1".  In the UI when I go to create "parent1", set a filter `has_primary_ip=False` and assign "child1" to it, I get the errors, but the expected error is hidden under the "Child Groups" nav tab under "Filter Options". See:

![image](https://user-images.githubusercontent.com/138052/216206925-fea262dd-161b-4d88-bd16-ac2fc6c23ff9.png)

Is this the confusion? Because I'll admit, this UX is kind of not great.

**Comment by ebusto** [comment]
@jathanism You're right, I flipped the expected and observed. Clearly I needed more coffee.

I didn't think to check the "child groups" tab for the error. I simply looked below as instructed, and saw a form without any error indications.

If the UI is improved a smidge so this error is front and center, that should reduce confusion.
