### ISSUE TITLE
Spike: Network Namespaces

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#3245]
As the Nautobot PO, I want an understanding of the requirements for namespaces so the team can begin to break down the work into several stories.

AC:
- What are the bounds for a namespace (IPAM only, devices, all of nautobot, etc)?
- What do namespaces do (provide uniqueness, etc)?
- What are the requirements for overlap, nesting, etc?

**Latest Design:** (see: https://github.com/nautobot/nautobot/issues/3245#issuecomment-1434806956)

![Untitled Diagram drawio-2](https://user-images.githubusercontent.com/31187/219696314-335ac810-c833-4e82-b95a-1a539622bbb3.png)

**Comment by lampwins** [comment]
Our stance on tenants is that they are to be used as ownership labels. Namespaces are closer to a non-functional requirement to be able to define bounds for uniqueness constraints.

**Comment by glennmatthews** [comment]
It seems to me that one of the first questions to answer is whether we're trying to design namespaces as an enabler (even if only in the future) of true multitenancy (not to be confused with the current Tenant/TenantGroup model) and resource isolation within Nautobot or whether that's explicitly out of scope. 

Namespaces for multitenancy:
- would need to apply to ALL Nautobot data models (with few/no exceptions)
- would need first-class support in user and permission definitions (i.e. make it really easy to restrict a user to only be able to access objects (of *any* type) that correspond to a specific namespace(s))

Namespaces for resource isolation within a single-tenant Nautobot instance:
- would only need to apply to data models that make sense to support namespacing (perhaps not models such as RIR, DeviceType, Provider, Location...?) though it might prove simpler from an implementation standpoint to make this an all-models feature anyway?
- would not require, but probably would still benefit from, first-class user/permission support, probably?

So maybe it's less of an issue than I was first thinking. Still worth further thought though.

**Comment by glennmatthews** [comment]
Broadly speaking, the purpose of a namespace (as currently scoped) as I see it is to allow for multiple database records to coexist that would otherwise fall afoul of appropriately-defined uniqueness constraints, and conversely to provide a baseline for defining uniqueness constraints that make it feasible to have natural keys for all models and minimize data duplication or ambiguity. The devil is in the details of course! Some thoughts:

- Perhaps host address + namespace should uniquely identify an IPAddress record (presuming requirements such as #2403 are met).
    - Host alone is not sufficient to uniquely identify an IPAddress because a network may have multiple distinct network zones, especially with reuse of RFC1918 address space.
    - Host + VRF is not sufficient because VRFs as a model are currently overloaded to mean both "network zone" and "device routing table instance" (e.g. device A might see a given connected network as being in its local VRF "red", while another device on the same network might map its connected interface to its local VRF "blue", but it's the same network and same IP address space at the network level); disambiguating these two meanings would help to address this problem. 
    - Note also issues such as #1508 that want VRFs to *not* necessarily be a uniqueness boundary for IPAddresses...
- VLANs, like VRFs, may be locally-significant to a device or may span a network. Currently a VID or VLAN name is unique in combination with a VLAN group (or no group at all), and VLAN groups are unique within a Location.
    - Explicitly scoping both of these to a namespace might help to more explicitly define boundaries and uniqueness?
    - Would VLANGroups become redundant with namespaces? Or is there a need for both still?
    - With locations being hierarchical, we probably need to revisit the uniqueness constraints for VLAN groups in any case so as to consider whether e.g. a VLAN group at the "Site" or "Region" level should permit or prevent creation of a similarly-named VLAN group at a child level such as "Building" or "Room"...
- Devices are currently uniquely defined by (among other constraints) location + tenant + name
   - In many networks, device names should *not* be reusable across multiple locations within the same network, and similarly device names may not be reusable across tenants within the same network either. Replacing both of these boundaries with an explicit namespace boundary would be tricky from a data migration standpoint but might be beneficial long-term
   - Same concern as VLANGroup in that Location is hierarchical whereas Site is not, should we allow "duplicate" Devices to exist at different levels of the same Location hierarchy? Probably not...
   - See also #2148, having a "live" namespace versus a "decommissioned" namespace might be one way to handle this?

**Comment by gsnider2195** [comment]
# Notes from office hours

## Models
- Namespace
- RD
- VRF
- VLAN
- Prefix
- IPAddress

## Uniqueness Constraints
- Prefix
  - Namespace
  - Network
  - Prefix Length
- IPAddress
  - Related Prefix through FK relationship
  - Network
  - Prefix Length
- RD
  - Namespace
  - Name/Label
- VRF
  - Namespace
  - Device
  - Name

## Relationships
- VRF
  - FK to RD
  - FK to Device
- Interface
  - FK to VRF
  - FK to IPAddress
- Prefix
  - FK to Namespace

**Comment by jvanderaa** [comment]
The notes are a whole lot of deeper things. When I look at this, I agree with @jedelman8 that Tenancy should be a close proximity to namespaces. I would at least want to have the ability to relate a tenant to a namespace as that "ownership" often comes along with it. 

In the past I have used Tenants to represent customers in a MSP environment. In that space, which I'm reading of the uniqueness of namespaces in the messaging of the last two entries. 

Would namespace allow for viewing only namespace, such as allowing a customer access to Nautobot data in a MSP environment?

**Comment by lampwins** [comment]
Namespace will have tenant as an attribute which will allow you denote ownership and permissions. One of the big problems with directly associating tenants to uniqueness boundaries is that tenants are used for multiple difference use cases and those often don't agree when you cross between MSP and single org environments, in terms of enforcing address space boundaries.

**Comment by bryanculver** [comment]
Proposed new data models and their relationships and uniqueness boundaries (designing against https://github.com/nautobot/nautobot/issues/3245#issuecomment-1433620448)

![Untitled Diagram drawio-2](https://user-images.githubusercontent.com/31187/219696133-5d452d6c-b2ce-427c-bc43-82e2cc1fdc2b.png)

**Comment by bryanculver** [comment]
We can validate this spike after shipping #3337. If we need to revisit these models we can either re-open this story or open another spike to go back to the drawing board.
