### ISSUE TITLE
don't see interface status field in API GET: /dcim/interfaces/?id<interafce_id>

### ISSUE THREAD

**Issue by milan2655** [nautobot/nautobot#3371]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.10
* Python version: 3.10.6
* Database platform, version: 14.6
* Middleware(s):

### Steps to Reproduce
1. call the next API: http://<nautobot_ip>/api/dcim/interfaces/?id<interafce_id>

to see status field:
           "status": {
                "value": "active",
                "label": "Active"
            },

no status field in respon!

**Comment by glennmatthews** [comment]
In 1.x the REST API [defaults to version 1.2](https://docs.nautobot.com/projects/core/en/stable/rest-api/overview/#default-versions-and-backward-compatibility) if unspecified. Try adding `?api_version=1.5` to the query, or setting `Accept: application/json; version=1.5` in your headers.

We're considering changing this default behavior in 2.0, see #2799.

**Comment by bryanculver** [comment]
> with api_version=1.5 is working! but why? do I need to set API version every time in a request?

Because that field was added in a newer version (https://docs.nautobot.com/projects/core/en/stable/release-notes/version-1.4/?h=interface+status#status-field-on-interface-vminterface-models-984) but for backward compatibility, we don't change behavior/responses when you upgrade to a newer version. There's no way of knowing when you first integrated with Nautobot or the first version you installed.

> one more question! is it possible to filter what fields to get in a response. for example, I am just interested in status and interface name fields.

This is the main advantage of GraphQL over REST. If the full response is unwanted you may want to check that out.

**Comment by milan2655** [comment]
thx for the hint with GraphQL.
