### ISSUE TITLE
Advanced filter on custom fields don't work

### ISSUE THREAD

**Issue by phoenixswiss** [nautobot/nautobot#3390]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.11
* Python version: 3.8.10
* Database platform, version: postgresql, Ubuntu 12.12-0ubuntu0.20.04.1
* Middleware(s): -

### Steps to Reproduce
1. Create a custom field (text, or selection) and assign it to interfaces ~~or devices~~
2. Fill the custom field with some information
3. Open the filter on the ~~device or~~ interface overview and switch to the advanced tab
4. Select the previously added field in the advanced filter, select a lookup type (any), and provide a value (not empty)
5. Press Apply

### Expected Behavior
Only the items matching the advanced filter will be shown in the list.

### Observed Behavior
An error will be shown:

```
Invalid filters were specified:
undefined
Unknown filter field
```

![image](https://user-images.githubusercontent.com/52887628/223093462-82d03010-f43f-4230-a4a2-7cc7a1dadb54.png)

### Additional information
If a custom field is selected on the Default filter tab, the filter works as expected.

**Comment by bryanculver** [comment]
I cannot reproduce this in demo or the latest release:

**Demo**

https://user-images.githubusercontent.com/31187/223143025-14a9bb47-0fac-4671-9c9a-e1fa0eae4735.mov


**Latest**

https://user-images.githubusercontent.com/31187/223142702-ab5b6de1-7574-4391-929b-44339bf79684.mov

**Comment by phoenixswiss** [comment]
Hi @bryanculver 

Thank you for your feedback. I've to correct my steps to reproduce. This issue occurs _at least with_ interfaces. Device filters are working fine as you showed in the video.

**Comment by itdependsnetworks** [comment]
I mucked with the url to show only what I think is relevant, but it results in `https://demo.nautobot.com/dcim/interfaces/?cf_role=&undefined=peer` as shown in the screenshot. 

<img width="764" alt="image" src="https://user-images.githubusercontent.com/9260483/223597035-ceb67c73-e7fc-47aa-b319-d35a9ed4d4a7.png">

**Comment by u1735067** [comment]
The error might be around https://github.com/nautobot/nautobot/blob/v1.5.14/nautobot/core/templates/generic/object_list.html#L252 and https://github.com/nautobot/nautobot/blob/v1.5.14/nautobot/core/templates/generic/object_list.html#L277, where there's no name attribute for advanced filters?

In v1.5.14, on model `Interface`, If you add (in advanced tab) a `not exact` filter on `description` with value `toto` for example:
```js
> $("#dynamic-filter-form, #default-filter form").serialize()
'[..]&form-2-lookup_field=description&form-2-lookup_type=description__n&undefined=toto&form-2-DELETE='
```

**Comment by bryanculver** [comment]
This is darling due to this line here: 

https://github.com/nautobot/nautobot/blob/98e4a52b8cf0c7dae19090fb539bcedceab83f8d/nautobot/core/api/views.py#L776

The DynamicFilterForm is attempting to asking what the rendered element should be for the given model and filter field. It's throwing an exception: `nautobot.dcim.models.device_components.Interface.device.RelatedObjectDoesNotExist: Interface has no device.` This is because since there is no form attached it has no way of getting what the widget should be and in some cases that filter doesn't have any widget available. It uses the model form but this has dependencies in the Interface case on a Device being associated since we don't have a "Create Interface" view that doesn't require Device already passed in.
