### ISSUE TITLE
Revisit New and Legacy UI Navigation

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot#3936]
- Legacy Navigation and New Navigation
    - 100% restore of existing nav menu functionality and location
    - Maintain two separate files

**Comment by glennmatthews** [comment]
- One file (`navigation.py`) per app, two constructs in that file - `menu_items` for v1, `navigation` for v2
- Possibly add new base classes for v2, since logic needs to differ (v2 menus don't contain `buttons`, v1 menus do)
   - v1 - NavMenuTab (plugin-definable), NavMenuGroup (non-nestable), NavMenuItem (w/ buttons)
   - v2 - NavContext (hard-coded list of these), NavGrouping (nestable), NavItem (w/o buttons)
- expose both class lists in `nautobot.apps` namespace!
- REST API endpoint returns v2 only, v1 is handled via template context

**Comment by bryanculver** [comment]
Closed via #3964
