### ISSUE TITLE
Dynamic Group issues after object modification

### ISSUE THREAD

**Issue by mzbroch** [nautobot/nautobot#3949]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.16
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Create two `Platform` objects:

```
- name: juniper_junos
  slug: juniper_junos
- name: cisco_ios
  slug: cisco_ios
```

2. Create dynamic group for `Device` object , in a `Platform` field select two created platforms. 

<img width="654" alt="Screenshot 2023-06-19 at 19 32 06" src="https://github.com/nautobot/nautobot/assets/16935122/3d50a8cc-ee2b-4e11-bc75-157d1d1dd075">

3. Modify `Platform` slug and name: change `cisco_ios` to `cisco-ios` (dash instead of underscore)

4. Attempt to modify dynamic group

5. After modifying Platform, `cisco-ios` is now not visible in a form. 

<img width="683" alt="Screenshot 2023-06-19 at 19 33 23" src="https://github.com/nautobot/nautobot/assets/16935122/f61e5067-c3a6-4021-b6f0-c5b99fe291bc">

### Expected Behavior

Clicking "Update" button results in modifying the dynamic group.

### Observed Behavior

Clicking "Update" button and saving dynamic group results with an error:

<img width="752" alt="Screenshot 2023-06-19 at 19 34 12" src="https://github.com/nautobot/nautobot/assets/16935122/37b4fcef-efe2-49dd-b07e-f5865e0bbff2">

**Comment by lampwins** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Product-64a8783b7a3f4b1225973a0c/issues/nautobot/nautobot/3949?planning-poker) with Zenhub @bryanculver @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by glennmatthews** [comment]
For context, DynamicGroup updates via the UI are done through multiple forms rather than a single unified form class - `DynamicGroupForm` only understands/validates/updates the base class attribute (`name`, `content_type`, etc.) while the `filter` is updated via a form dynamically constructed by `instance.generate_filter_form()`. The issue here is that because the underlying data changed, the existing DynamicGroup instance's `filter` data is no longer valid (in this specific case it references a `slug` that no longer exists, but the same issue would happen for e.g. a UUID-based filter that referenced a now-deleted object), and so when the `DynamicGroupForm.is_valid()` is called, calling the `instance.full_clean()` fails *before the generated "filter_form" has a chance to update the instance to a new (valid) filter value*.

Most likely the required fix here will be to change the form definitions and/or code flow in `DynamicGroupEditView.post()` so that there's only a single form class/object that handles the updating/validation of the entire DynamicGroup instance data in a single pass. This will be pretty invasive code-wise but I think it's necessary.
