### ISSUE TITLE
Within edit view of virtual chassis, button indicates create instead of update

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#398]
### Environment
* Python version: 3.7
* Nautobot version: 1.0

When going to update a chassis, the button indicates create, instead of udpate

### Steps to Reproduce
1. Create a virtual chassis
2. Edit the virtual chassis
3. View the button on the bottom

### Expected Behavior

When editing a device chassis, the button should indicate "update".

### Observed Behavior
When editing a device chassis, the button says "create" instead of update.
![image](https://user-images.githubusercontent.com/9260483/116818015-307d4880-ab37-11eb-9b4e-bec599651fa7.png)

**Comment by smk4664** [comment]
This is due to VIrtualChassisEditView no longer inheriting from ObjectEditView.  https://github.com/nautobot/nautobot/commit/a4019be28c8c6af7e2b134d6750877bf696f3963#diff-2d8f796155b3fffa107a5417c20e7699d37c9b49ab50d7001c0c4eab2663dc0eL2106

ObjectEditView adds `"editing": obj.present_in_database` to the render.

**Comment by smk4664** [comment]
I can take this one.
