### ISSUE TITLE
Installation metrics has long timeout and blocks Nautobot startup

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#4241]
### Environment
* Nautobot version: 1.6.0
* Python version: 3.8
* Database platform, version: PostgresQL 14
* Middleware(s): -

### Steps to Reproduce
1. Start Nautobot with installation metrics enabled (default) in an environment where Nautobot Cloud can't be reached

### Expected Behavior
Nautobot starts up as quickly as usual, with either asynchronous communication to Nautobot cloud or an aggressive timeout.

### Observed Behavior
Nautobot hangs for at least 5 minutes, I just disabled the setting at that point.

**Comment by bryanculver** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Nautobot-Core-Engineering-64a875e74842500d9e80e23e/issues/nautobot/nautobot/4241?planning-poker) with Zenhub @glennmatthews @gsnider2195 @HanlinMiao @jathanism @timizuoebideri1

**Comment by gsnider2195** [comment]
Is the plan to make this asynchronous or just add a timeout?

**Comment by bryanculver** [comment]
@gsnider2195 I would think make it asynchronous because it would entirely get around any concerns with timeouts but if it's not possible or would require an entire rewrite, a significantly shorter timeout would be fine.

**Comment by nniehoff** [comment]
FYI in certain environments we are also seeing Nautobot fail the post_upgrade because the SSL cert at nautobot.cloud... I suspect in these environments the organization proxies ssl traffic or for whatever reason doesn't trust the Let's Encrypt CAs.  In any case I feel like these errors should be non-blocking and silently ignored, maybe just a warning
