### ISSUE TITLE
Status Changes Do Not Appear in Difference Section of Changelog

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#427]
### Environment
* Python version: demo.nautobot.com
* Nautobot version: 1.0.1

### Steps to Reproduce
1. Edit a site status 
2. Navigate to changelog
3. Observe No differences being shown

### Expected Behavior

Expected to have the status field show up under change as though you had changed the shipping address of a site

### Observed Behavior

No changes appear in the change log

**Comment by jathanism** [comment]
This is only the case on the Demo because the initial objects are imported using the ORM which does not result "create" change log events. If you edit an object to create a change event, and then edit it again, the "Difference" table will be populated as expected.

![dcim___site_ams_updated_by_demo_-_Nautobot](https://user-images.githubusercontent.com/138052/118005137-f9f5b980-b2fe-11eb-8e87-ce91e5676d95.png)
