### ISSUE TITLE
Allow non-english characters in Composite Key

### ISSUE THREAD

**Issue by apast0r** [nautobot/nautobot#4368]
### Environment
* Nautobot version (Docker tag too if applicable):  v2.0.0rc2
* Python version: python 3.11
* Database platform, version: 8.0.33
* Middleware(s):

### Steps to Reproduce
1. Create any location with non English character. Example: "España".
2. Create a rack and set his location to "España".
3. Create a device and assign to the rack.
4. Go to Advanced Tab of the device to see the Composite Key.

### Expected Behavior
The Composite Key sould be: "device;rack;España"

### Observed Behavior
The Composite Key is: "device;%00;Espa%C3%B1a"

This also happen in the Export generator.

**Comment by bryanculver** [comment]
@apast0r We are considering making two changes related to this:

- #4346 (note it would remove composite key and not be usable for lookup)
- #4367 (inverse of #3794)

The second story should not perform any URL-safe encoding of strings so should support non-English characters, but since we will be eliminating the Composite Key itself, I wanted to ensure your needs would be addressed.

**Comment by jathanism** [comment]
@apast0r Hello! In the working I'm doing in #4439, it will be a bit of a compromise, where instead of stripping the characters, they have accents removed. So your example would result in `España` becoming `espana` instead of `Espa%C3%B1a`.

**Comment by bryanculver** [comment]
@apast0r Please take a look at RC3 which now implements `natural_slug` and better handles non-English characters. Exporting the non-URL encoded payload by breaking out the natural keys as discrete columns will be in the final 2.0 release.

**Comment by apast0r** [comment]
hi @bryanculver, I will update our test environment with the last 2.0 RC3.
