### ISSUE TITLE
Rename dummy plugin to "example" plugin that is used within docs and core test suite

### ISSUE THREAD

**Issue by jathanism** [nautobot/nautobot#443]
### Proposed Changes

We already did the work to break out `nautobot.extras.tests.dummy_plugin` and its corresponding parts to the `examples` directory in the project root so that it is installed like a normal plugin would be and included as a dependency in `pyproject.toml`.

### Justification

The name "Dummy" makes it seem like it doesn't do anything, but we should rename it to "Example" so it indicates more clearly that it is actually a reference example of an actual plugin, that exercises most of the available features.

This will set us up for the future to continue to extend and test plugin features while also showcasing them explicitly as examples.

**Comment by glennmatthews** [comment]
While I agree with splitting the plugin out into a proper Python package, I'm leaning a bit towards keeping it as a separate subdirectory (`/examples/dummy_plugin/`?) in the main repository rather than creating a separate repository. My reasoning is just that in most cases the dummy plugin should be versioned in lockstep with Nautobot itself, rather than having separate releases. Open to discussion on this point though.

**Comment by FragmentedPacket** [comment]
I agree with @glennmatthew, but not entirely sure how it'll work with tests.

This is a good thing to fix though as I ran into issues testing in #395 so thanks for creating this issue!

**Comment by glennmatthews** [comment]
@jathanism Is this resolved by #474?

**Comment by jathanism** [comment]
I just reworked this to rename the plugin and enhancing the documentation instead of publishing it to PyPI.

**Comment by glennmatthews** [comment]
Implemented in `next` (1.3.0) by #1235.
