### ISSUE TITLE
Role screen related object tables pagination selection overlap with the table below it. 

### ISSUE THREAD

**Issue by scetron** [nautobot/nautobot#4704]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.0
* Python version: 3.11
* Database platform, version: postgres/na
* Middleware(s):

### Steps to Reproduce
1. Create a role
2. View the role detail screen
3.

### Expected Behavior

UI elements to not overlap

### Observed Behavior

Pagination selector for each table overlaps with the table below it. See screenshot 
![Screenshot 2023-10-24 at 16 48 43](https://github.com/nautobot/nautobot/assets/10200477/ffae8f30-4c06-4755-acd2-349c6bd67b04)

**Comment by timizuoebideri1** [comment]
The issue here is caused by the `pull-right` CSS class, which makes a `div` float and affects the `div` positioned below it. Here are two solutions:

1. Remove `pull-right` from the top `div`. The pagination box will still be on the right, and the parent `div` will occupy 100% width.
https://github.com/nautobot/nautobot/blob/f56e49ff54b1bd088945c2765acbfe023e139f44/nautobot/core/templates/inc/paginator.html#L3-L6


2. Apply `clear: both` to all `div`'s below the pagination to prevent overlapping.

https://github.com/nautobot/nautobot/blob/5da5c04c8e2c77b81a88cf42d5e753eb5a49c72a/nautobot/extras/templates/extras/role_retrieve.html#L62-L63

i.e 
```html
    {% include 'inc/paginator.html' with paginator=vlan_table.paginator page=device_table.page %}
    <div class="panel panel-default clear" style="clear: both">
```

**Comment by scetron** [comment]
Are these the only two acceptable solutions? Both feel a bit off. Removing the pull-right will also affect everywhere else the paginator template is used. 

I also noticed that each table, the `paginator=vlan_table.paginator `instead of a `paginator` for the specific table, is `device_table.paginator` an invalid `paginator`?

**Comment by scetron** [comment]
Ahh well, looks like removing the pull-right doesn't effect other tables on other pages...
