### ISSUE TITLE
Computed Fields with invalid slugs are not converted to valid keys during 2.0 migration

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#4854]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.4 -> 2.0.5
* Python version: 3.10.12
* Database platform, version: Postgres 14.9
* Middleware(s):

### Steps to Reproduce
1. On Nautobot 1.6.4 create a computed field with dashes in the slug instead of underscores (e.g. `bad-cpf`)
2. Upgrade Nautobot to 2.0
3. Try and load the GraphQL UI

### Expected Behavior
GraphQL UI loads

### Observed Behavior
```
AssertionError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "cpf_bad-cpf" does not.
```

**Comment by HanlinMiao** [comment]
It is the intended behavior of computed field slugs/keys. Changing the dash to underscore should fix the issue.
We should have enforced the pattern in the migrations but for now can you try `cpf.key.replace("-", "_")` and then `cpf.save()`

**Comment by glennmatthews** [comment]
The issue here is at least twofold:

- Validation of the `key` for ComputedField, CustomField, and Relationship is only done in `clean()` so any direct ORM interaction (`ComputedField.objects.create()` or `ComputedField(...).save()`) can result in invalid keys being set. Possible fix here: move that enforcement from `clean()` to `save()`?
- When invalid keys are present, the GraphQL UI throws an exception and fails to load; it should instead log a warning/error message to syslog but not prevent the UI from loading at all.

**Comment by lampwins** [comment]
Check if `get_or_create()` calls save.
