### ISSUE TITLE
VRF API Endpoint slow

### ISSUE THREAD

**Issue by netgitdom** [nautobot/nautobot#4898]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0.5
* Python version: 3.8.18
* Database platform, version: Postgres 13
* Running on an AWS Workspace

### Steps to Reproduce
1. Create VRFs with some CustomFields, RTs and Prefixes (for us around 200 VRFs)
2. Add Prefixes (for us around 75.000)
3. Open the API Endpoint via Browser $NAUTOBOT/api/ipam/vrfs/

### Expected Behavior
I would expect at least the same loading times like with 1.6 with this data set (1 second).

### Observed Behavior
The API Endpoint with 2.0.5 (and 2.0.3) took about 8 seconds to load.
To open the VRFs within the GUI ($NAUTOBOT/ipam/vrfs) is faster and took about 1,8 seconds ( < 1 Second with 1.6)

This behavior may be related to another performance issue we noticed in the GUI Prefix view. If I try to filter the list of Prefixes with the assigned VRF it took these bespoke 8 seconds to show me the list of VRFs.

I'll add the output of the SQL commands from the Django toolbar, maybe you can see something helpful in there.

[nautobot_2.0.5_vrf_api_issue.txt](https://github.com/nautobot/nautobot/files/13529590/nautobot_2.0.5_vrf_api_issue.txt)

**Comment by glennmatthews** [comment]
I think a big reason the 2.x REST API response is noticeably slower than 1.x is that in 1.x we only serialized the related `import_targets` and `export_targets` M2M fields, but in 2.x we also include the `devices`, `virtual_machines`, and `prefixes` related to each VRF. Updating `VRFViewSet.queryset` to include `prefetch_related("devices", "virtual_machines", "prefixes")` cuts the number of distinct SQL queries by about 2/3 in my local testing but, surprisingly, doesn't speed up the overall response time noticeably otherwise. I think we need to look at how we're handling serialization of M2M fields at depth 0 as I'm guessing we're doing some inefficient re-calculations when there are a large number of related objects.

**Comment by glennmatthews** [comment]
As one data point, disabling the calculation of absolute URLs for all related objects:

```diff
diff --git a/nautobot/core/api/fields.py b/nautobot/core/api/fields.py
index d12bd6389..fb0e74d82 100644
--- a/nautobot/core/api/fields.py
+++ b/nautobot/core/api/fields.py
@@ -206,7 +206,7 @@ class NautobotHyperlinkedRelatedField(WritableSerializerMixin, serializers.Hyper
 
     def to_representation(self, value):
         """Convert URL representation to a brief nested representation."""
-        url = super().to_representation(value)
+        url = ""  # super().to_representation(value)
 
         # nested serializer provides an instance
         if isinstance(value, Model):
```

appears to substantially improve the response time of the VRF REST API at this sort of scale. It is known that DRF's `reverse()` calculation is not particularly performant, but it's nevertheless surprising to me that the impact is that significant.
