### ISSUE TITLE
`Location.base_site` is implemented inefficiently

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#4921]
### Environment
* Nautobot version: 1.6.6
* Python version: 3.8
* Database platform, version: PostgresQL 16
* Middleware(s): -

### Steps to Reproduce
1. Create a location type hierarchy
2. Create locations for the types in the hierarchy
3. Call `Location.base_site` on any of them

### Expected Behavior

The `Location.parent` foreign key is used to traverse the tree to the root.

### Observed Behavior

`Location.ancestors` is used, which has to calculate the entire tree.

**Comment by gsnider2195** [comment]
Is it more efficient to perform the multiple sql queries to follow the parent foreign key all the way to the root rather than use `ancestors().first()`? I would assume that run multiple sql queries and going back and forth between python and the database would be slower than doing it all in the CTE query.

**Comment by glennmatthews** [comment]
If I understand my conversations with Leo correctly, at high scale (10000+ Locations), running the CTE to annotate *all* Locations in order to construct the ancestors list for one instance is markedly more expensive in total than the multiple individual queries to walk the (relatively shallow) parent keys from the instance itself.

**Comment by glennmatthews** [comment]
Fixed for 1.6 by #4918.
