### ISSUE TITLE
Dynamic Groups - Invalid filter 'tag' detected with value ['test-dev']

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#4999]
### Environment
* Nautobot version 7d40487ce037 (v2.0.6b1)
* Python version: 3.10
* Database platform, version: postgres:14
* Middleware(s):

### Steps to Reproduce
1. Define a Dynamic Group with a 'Tag' as criteria in 'Filter Fields'
2. Klick 'Update'
3.

The Dynamic Group and the Tag are migrated from Nautobot v1.4.10

### Expected Behavior
Dynamic Group will be saved.

This is the Tag definition used:
![image](https://github.com/nautobot/nautobot/assets/8406301/17e96bb9-f67d-4bfc-8795-ff215f9b4848)

### Observed Behavior
Editing dynamic group Test-Switches
  Errors
    Invalid filter 'tag' detected with value ['test-dev']

**Comment by gsnider2195** [comment]
It looks like you might be encountering an issue with the 2.0 upgrade and dynamic group filters. We have documentation on that [here](https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/upgrading/from-v1/upgrading-from-nautobot-v1/?h=dynamic#ui-graphql-and-rest-api-filter-changes) but it's easy to miss it:

> Sweeping changes were made to model filter fields. In some cases this may invalidate or make subtle changes to existing DynamicGroup, GraphQLQuery or Relationship instances' filter data. Please utilize the [nautobot-server audit_dynamic_groups](https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/tools/nautobot-server/#audit_dynamic_groups) and [nautobot-server audit_graphql_queries](https://docs.nautobot.com/projects/core/en/stable/user-guide/administration/tools/nautobot-server/#audit_graphql_queries) helper commands when you are cleaning up DynamicGroup and GraphQLQuery filter data. You should run this command after your Nautobot instance is upgraded to v2.x successfully. The helper commands will not catch all possible issues, but they will catch some common ones. You should review all of your DynamicGroup filter data and GraphQLQuery query data after the upgrade to ensure that they are still valid. At the time of this writing, an audit helper command for Relationship filter data is not yet available.

I believe the root cause of this issue is where we switched `TagFilter` from `slug` to `name` [here](https://github.com/nautobot/nautobot/commit/5da5c04c8e2c77b81a88cf42d5e753eb5a49c72a#diff-409e68a3e0f8c03af6b1c3b6c5c4c66678d5a02f085a73aeaead44b55b4f6368L400).

**Comment by jifox** [comment]
@gsnider2195 Yes, you are right. It works well after deleting and adding the Dynamic Group with same name and filter definition.
