### ISSUE TITLE
Jobs Docs: Document Reserved Keywords Such as "Name"

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#5094]
### Proposed Changes

Update docs for Jobs in the Jobs Developer Guides.

### Justification

Was getting an error of:

```
TypeError: object of type 'StringVar' has no len()
```

Such as an example job:

```python
class MyJob(Job):
    """Job to create a specified Rack."""

    name = StringVar(label="Rack Name", description="Name of the rack")
```

**Comment by jvanderaa** [comment]
Unless they should be somewhere else - https://docs.nautobot.com/projects/core/en/stable/development/jobs/?h=stringvar#variables

**Comment by jvanderaa** [comment]
It was found that `name` appears to be a reserved keyword in this, so would like to have the list of reserved keywords that we shouldn't use.

**Comment by glennmatthews** [comment]
Fair request. There are unfortunately a lot of these, some inherent to the base Celery `Task` class and more added by Nautobot's `BaseJob` subclass.

It'd be a breaking change, but I'd prefer to address this long-term by moving the user-input variables into an explicit attribute grouping of their own, rather than having them declared at class-level, which currently requires Nautobot to always introspect every class attribute to see which ones are subclasses of `ScriptVariable` and has this risk of accidental clobbering as you describe above. Something like:

```python
class MyJob(Job):
    class Meta:
        name = "My Job"
        description = "Job to create a specified Rack."
        variables = {
            "name": StringVar(...)
        }
```

**Comment by glennmatthews** [comment]
Related: #4761.

**Comment by glennmatthews** [comment]
Just going by `BaseJob`, without looking upstream to `Task`, we currently have:

```
__init__
__call__
__str__
on_bound
shadow_name
before_start
run
on_success
on_retry
on_failure
after_return
apply
file_path
class_path
class_path_dotted
class_path_js_escaped
grouping
_get_meta_attr_and_assert_type
name
description
description_first_line
dryrun_default
hidden
field_order
read_only
approval_required
soft_time_limit
time_limit
has_sensitive_variables
supports_dryrun
task_queues
properties_dict
registered_name
_get_vars
_get_file_vars
as_form_class
as_form
clear_cache
job_model
job_result
celery_kwargs
user
serialize_data
deserialize_data
validate_data
prepare_job_kwargs
_load_file_from_proxy
_save_file_to_proxy
_delete_file_proxies
load_yaml
load_json
create_file
```
