### ISSUE TITLE
ghcr.io/nautobot/nautobot:latest points to a 2.0.0 image

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#5171]
When you run `docker run ghcr.io/nautobot/nautobot` you shouldn't get such an outdated image. Also, `docker.io/networktocode/nautobot:latest` doesn't exist so if you run `docker pull networktocode/nautobot` you get an error:

```
$ docker pull networktocode/nautobot
Using default tag: latest
Error response from daemon: manifest for networktocode/nautobot:latest not found: manifest unknown: manifest unknown
```

**Comment by glennmatthews** [comment]
Related: #4167.

**Comment by glennmatthews** [comment]
Also #4689.

**Comment by bryanculver** [comment]
- `ghcr.io/nautobot/nautobot` (continued as **GH Nautobot**) is a by-product of the package registry association with this Github Org (we could get a token from https://github.com/networktocode to publish to `ghcr.io/networktocode`) 
- `docker.io/networktocode/nautobot` (continued as **DH Nautobot**) I think is a hold-over in how we first created an org in Docker. We should probably consider mirroring to a Nautobot DH org at some point


Assume "as far as I know" and "as far as I remember" for the following:
- `latest` was never a tag in the **DH Nautobot** because tagging and pushing were done locally and every tag needed to be explicit, DH doesn't do it automagically
- `latest` was a tag in **GH Nautobot** because the CI action made it easy or automatic
- **GH Nautobot** was introduced to avoid some rate-limiting from CI pulling from DH: https://networktocode-llc.slack.com/archives/C01J0MSTMAB/p1619701942437300
- Apps used to default to testing against `latest` instead of a particular major/minor: https://github.com/nautobot/nautobot-plugin-chatops-panorama/blob/17760e85692a2af74dadd8a7775c2136dfe79637/tasks.py#L55 which would have caused a breaking change until those all got updated (a lot of the cookiecutter drift management should be/have addressed this) and some explicitly tested it in their CI: https://github.com/nautobot/nautobot-plugin-ssot-servicenow/blob/b276ec146fdf7056fe7f199bbb37d14f91cf1ff9/.github/workflows/ci.yml#L121
- Upstream testing never used `latest`: https://github.com/nautobot/nautobot/commit/760e65776b67b7f93134576c3c715880994e1b42#diff-873cc477c98bba79dea0471097835bf122baacd91e6867187db62eb8acee3184R22

IMHO:
- `latest` should be set in both registries
- `latest` should be the latest stable release (so it would move major version upon it's release)
- `stable` would be redundant/synonymous with `latest`
