### ISSUE TITLE
Delete all OOM

### ISSUE THREAD

**Issue by rifen** [nautobot/nautobot#5321]
### Environment
* Nautobot version (Docker tag too if applicable): ghcr.io/nautobot/nautobot:2.1.4-py3.9
* Python version: 3.9.18
* Database platform, version: postgres:13
* Middleware(s): uWSGI/nginx - whatever comes with the container + custome uWSGI config

### Steps to Reproduce
1. Select # of (IP's) in this case 56k:
![image](https://github.com/nautobot/nautobot/assets/10360333/cdba4afb-1590-4d76-8f38-cdccf3594f1b)
2. Press Delete all
3. Get error:
![image](https://github.com/nautobot/nautobot/assets/10360333/47824dc1-44a4-42e4-aea0-019d721241bb)

### Expected Behavior
I would just get a list viewing all the IP's with the option to delete them all. Similar to deleting any other object.

### Observed Behavior
<class 'MemoryError'>

**Comment by glennmatthews** [comment]
Thanks for the report!

I'm going to point the finger at https://github.com/nautobot/nautobot/blob/develop/nautobot/core/views/generic.py#L1197-L1202 as a starting point. It seems to me that if we're using `_all`, we should just carry that flag forward, rather than trying to construct a `pk_list` consisting of 56000 individual entries.

**Comment by itdependsnetworks** [comment]
Please consider this at the same time: https://github.com/nautobot/nautobot-app-golden-config/blob/4de3f3778596bfac6ab2318373b0d8aee2323bcf/nautobot_golden_config/views.py#L281-L322

**Comment by glennmatthews** [comment]
> Please consider this at the same time: https://github.com/nautobot/nautobot-app-golden-config/blob/4de3f3778596bfac6ab2318373b0d8aee2323bcf/nautobot_golden_config/views.py#L281-L322

@itdependsnetworks I'm not sure I follow - what about that function are you asking us to consider?

**Comment by glennmatthews** [comment]
Related: #2459.

**Comment by itdependsnetworks** [comment]
> > Please consider this at the same time: https://github.com/nautobot/nautobot-app-golden-config/blob/4de3f3778596bfac6ab2318373b0d8aee2323bcf/nautobot_golden_config/views.py#L281-L322
> 
> @itdependsnetworks I'm not sure I follow - what about that function are you asking us to consider?

@glennmatthews in GC, we have used the same pattern, so if you are adjusting this pattern here, just ask to consider if it will still work for GC.

**Comment by glennmatthews** [comment]
Also an issue: the rendered confirmation page is *not* paginated - so even if the pk_list isn't the issue, Django will probably tip over trying to render a non-paginated table of 55000 records in a single page.

**Comment by glennmatthews** [comment]
For both "edit all" and "delete all" cases, instead of a secondary page, we could possibly use modals - a simple "confirmation" modal for "delete all", and a modal containing the BulkEditForm for "edit all"?

For the "edit selected" and "Delete selected" cases, we could keep the existing UI for now.

**Comment by glennmatthews** [comment]
Alternately, instead of a modal, just skip rendering the table of related objects in the confirmation page in the "select all" case, and just list the filters and total count in its place?
