### ISSUE TITLE
Refactor Dynamic Group mechanics

### ISSUE THREAD

**Issue by lampwins** [nautobot/nautobot#5473]
As a Nautobot Engineer, I want the dynamic group functionality to be refactored such that membership resolution is cached using static groups, so that critic performance issues do not prevent the usage of dynamic groups.

The filering logic and UX for dynamic groups should remain as-is, but the primary goal of this effort is to cache the membership of groups such that the access use case is optimized.

We should allow saved groups to be "hidden" such that these dynamic group static groups are not visible and do not get in the way of "real" static groups.

**Comment by lampwins** [comment]
So I was thinking about this after the meeting and I fear we are starting off to complex. From past experience with cacheops, I think the biggest problem to the user was the lack of understanding/visibility that the cache was outdated and not having an easy way to remediate.

On that hypothesis, I wonder if we would be better off (to start with) by making this a simple time based cache but focusing on the state visibility to the user. Make the time configurable, but default to say 15 minutes. So every 15 minutes, we have a scheduled system job that refreshes the groups. On the dynamic group detail view, clearly show the user the last time the group was updated and give them a button to do an ad-hoc update. Also provide a utility function for SSoT or app authors to manually trigger an update if they so choose.

I think that gives us a solid base to stand on and then expand from there as more well defined use cases arise. If we start too complex, I think we doom ourselves to having to constantly fix cache bugs in a paradigm that folks don't really need or want, or at least one which is prematurely optimized.

**Comment by bryanculver** [comment]
Could this:

- https://github.com/nautobot/nautobot/blob/2e6a144df6fe88a559982eb2506783817235df44/nautobot/extras/signals.py#L416-L442
- https://github.com/nautobot/nautobot/blob/2e6a144df6fe88a559982eb2506783817235df44/nautobot/extras/models/groups.py#L331-L359

be updated to save onto DB instead of Redis? It already leverages a timeout.

And this updated to just be a reverse generic foreign key M2M to said DB-backed cache: https://github.com/nautobot/nautobot/blob/2e6a144df6fe88a559982eb2506783817235df44/nautobot/extras/models/mixins.py#L23-L38
