### ISSUE TITLE
Change maximum allowed value for Integer Type in Custom Fields

### ISSUE THREAD

**Issue by sirtux** [nautobot/nautobot#569]
### Environment
* Python version: 3.9.1
* Nautobot version: v1.0.2

### Proposed Functionality
The maximum value of an Integer used in a CustomField should be bigger than 2147483647.

### Use Case
I'd like to have a custom field ASN, which by nature needs to go up to 4294967294.

### Database Changes
Unknown

### External Dependencies
None

**Comment by jathanism** [comment]
Hmmm great idea. This would likely be as "simple" as changing `CustomField.validation_minimum/validation_maximum` fields from `PositiveIntegerField` types to [`PositiveBigIntegerField`](https://docs.djangoproject.com/en/3.2/ref/models/fields/#positivebigintegerfield). Of course we'd still have to account for testing, and to make sure that the schema migration for the field type also includes a data migration. Because of this, we likely wouldn't be able to implement this until v1.2 at the earliest.

**Comment by Joezeppe** [comment]
I can work on this.

**Comment by lampwins** [comment]
@Joezeppe thanks Sammy, go for it!
