### ISSUE TITLE
Banner replication takes over 24hrs to complete

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot#5795]
Note: this was working in 1.5.19, but stopped in later releases from 1.6.8 onward
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.8
* Python version: 
* Database platform, version: Postgres
* Middleware(s):

design:
Nautobot RW → (Connect) → Postgres RW
Postgres RW → (Replicate) → Postgres RO
Nautobot RO → (Connect) → Postgres RO

### Steps to Reproduce
1. Change the Nautobot banner in the Nautobot RW instance
2. Wait 24hrs
3. Banner changes in the Nautobot RO instance

### Expected Behavior
Immediate change as soon as the update is made.

### Observed Behavior
Banner remains unchanged.

### Additional Steps performed per support ticket
1 - Change the banner on the RW instance
2 - Restart Nautobot RO
3 - Verify the banner wasn’t changed on RO (private browser window, no caching, no cookies)
4 - Run nautobot-server invalidate all on Nautobot RO
5 - Verify the banner wasn’t changed on RO (private browser window, no caching, no cookies)
6 - Restart Nautobot RO
7 - Verify the banner wasn’t changed on RO (private browser window, no caching, no cookies)

**Comment by gsnider2195** [comment]
Which banner are you changing where you're seeing this behavior? Is it one of these constance config settings?

- `BANNER_BOTTOM`
- `BANNER_LOGIN`
- `BANNER_TOP`

**Comment by chrisguel** [comment]
`BANNER_TOP`

**Comment by gsnider2195** [comment]
Thanks @chrisguel 

Next steps would be to determine how long it's taking for these configuration changes to take effect on the RW database and then the RO database. If you could provide the output of `nautobot-server constance list` on both nautobot servers and the `constance_constance` table on both databases, that will help pinpoint where the problem is originating from. The database values are base64 encoded so if you need to sanitize the banner before posting, please use a base64 decoder on the data first.

Also, can you provide the values for your `CONSTANCE_BACKEND` setting on both nautobot servers?

**Comment by lampwins** [comment]
Updates in internal ticket. Check with John and/or Chris.

**Comment by glennmatthews** [comment]
If I'm reading the Constance code correctly, at app startup it caches all existing settings with a timeout of 24 hours. Worse though, when a config change is made through Constance, it sets the cache for that setting with _no timeout at all_. Might need to unset `CONSTANCE_DATABASE_CACHE_BACKEND` on the RO replica instance as a workaround.

**Comment by glennmatthews** [comment]
This is "working as configured" if the RO Nautobot instance has a separate Redis instance of its own and is using Nautobot's default Constance configuration. If a more rapid clearing of the cache on the RO instance is desired, configuring its `CONSTANCE_DATABASE_CACHE_AUTOFILL_TIMEOUT` setting to a lower value (60 seconds, rather than the default 86400 seconds, might be a reasonable compromise) should address this behavior.

We should probably:

1) Document the `CONSTANCE_DATABASE_CACHE_AUTOFILL_TIMEOUT` setting in the Nautobot documentation.
2) Configure it to a lower value than the 86400-second default, bearing in mind the performance tradeoffs of doing so.
