### ISSUE TITLE
[2.3] Custom Field on ObjectEditView do not use BootstrapMixin

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#5967]
### Environment
* Nautobot version (Docker tag too if applicable): Next
* Python version: 3.11
* Database platform, version: N/A
* Middleware(s):

### Steps to Reproduce
1. Create a custom field
2. Apply the following to base.css
```
:root {
    --navbar-transition-duration: 350ms;
    color-scheme: light dark;
}

@media (prefers-color-scheme: light) {
    .element {
      color: black;
      background-color: white;
    }
  }
  
  @media (prefers-color-scheme: dark) {
    .element {
      color: white;
      background-color: black;
    }
  }
```
3. Edit an object that has a custom field.

### Expected Behavior
The custom field loads and appears like other fields

### Observed Behavior
The custom field is blacked out.  This is due to a missing class definition on the field `class="form-control"` is not on the fields attributes.

**Comment by glennmatthews** [comment]
Appears to have been broken by the change in mixin order in #5668 (https://github.com/nautobot/nautobot/pull/5668/files#diff-37550f2cee9ccba0e981fe201cec2a6465ec95e712c6d926e0a0e78fb81d513eR26-R33) such that `BootstrapMixin` now comes after `CustomFieldModelFormMixin` instead of before it. This portion of the change needs to be reverted.
