### ISSUE TITLE
Saved views not displayed in Saved View drop down for Rack Elevation Table view

### ISSUE THREAD

**Issue by djhoward12** [nautobot/nautobot#6217]
### Environment
* Nautobot version 2.3.2
* Python version: 2.11
* Database platform, version: Postgres 

### Steps to Reproduce
1. Navigate to `/dcim/rack-elevations/`
2. Click Saved Views drop down and click `Save as New View`
3.  Fill out form and recieve the message `Successfully created new Saved View 'Test View'.`
4. Click on Saved Views drop down and created view is not present. 
![Screenshot 2024-09-14 at 12 20 08 PM](https://github.com/user-attachments/assets/200b5564-536a-404e-b7e4-0d9071c9199b)
5. Verify Saved view was created in change log
![Screenshot 2024-09-14 at 12 21 47 PM](https://github.com/user-attachments/assets/3d9657d0-8afd-4e41-b9d8-2cad4ab8f177)
6. Clicking the URL in the change log redirects to the saved elevation view. I verified that if filters are set they are present, but the name does not appear to the right of Rack Elevation like it does with other saved views.
7. Verified on local docker install and demo.nautobot.com

### Expected Behavior
I expect to be able to create, share and reuse saved views for elevation for ease of visualizing available rack space by location.

### Observed Behavior
Saved views are not saved in the Saved View drop down

**Comment by HanlinMiao** [comment]
Thank you for the submission @djhoward12.
It seems like we are using the given [model](https://github.com/nautobot/nautobot/blob/develop/nautobot/core/views/generic.py#L305) to determine the view_name in the current view, where as [RackElevationListView](https://github.com/nautobot/nautobot/blob/develop/nautobot/dcim/views.py#L565-L570) has the view_name of `dcim:rack_elevation_list` and the model `Rack` so that we are looking for `SavedView` instances with the view_name `dcim:rack_list` instead of the correct `dcim:rack_elevation_list`.
