### ISSUE TITLE
Prefix summary table shows locations count in table. Previous 1:1 behaviour displayed actual location name

### ISSUE THREAD

**Issue by steve-hodgkiss** [nautobot/nautobot#6231]
### As ...

Ozzie - Operator

### I want ...

An easy way of seeing at a glance which prefixes are assigned to which location in a summarised table. New behaviour now that prefixes can be assigned to many locations is to display the count in the "locations" column. 
https://demo.nautobot.com/ipam/prefixes/ for example.
This change was made to make the table cope with prefixes assigned to very many locations but has made the table less useful for the majority of cases where prefixes are assigned to a single location. Suggest a compromise:
* if the prefix is assigned to one location display the location name
* if the prefix is assigned to multiple locations display the count

### So that ...

The current summary table displays a more useful view showing which prefixes are assigned to which location

### I know this is done when...

The prefix summary table as per https://demo.nautobot.com/ipam/prefixes/ behaves like the previous behaviour unless a prefix is assigned to more than one location

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

### Database Changes

UI change only - no database changes required

**Comment by glennmatthews** [comment]
See also #5773

**Comment by steve-hodgkiss** [comment]
Yes that issue addresses multiple shortcomings in the UI to avoid multiple click-throughs to see the data. The changes to the IPAM prefix view is very pressing as it has significantly reduced the usability of this view from previous behaviour.

**Comment by digital-fortress** [comment]
Team , will you have a solution for this anytime soon?

**Comment by glennmatthews** [comment]
If I'm understanding https://github.com/django/django/commit/242499f2dc2bf24a9a5c855690a2e13d3303581a correctly, it should be possible to efficiently get the first N (say, 1 or 2) associated Locations for each Prefix in the table view with an appropriate `prefetch_related(Prefetch...)` call, which would make it acceptable performance-wise to implement this behavior. (Doing an unbounded `prefetch_related("locations")` would be problematic since it could potentially fetch a huge number of Locations for each Prefix in the table)

**Comment by digital-fortress** [comment]
Developers do not understand the difficulty of not having the location view. At least if prefixes are only on a single site, display it please.

**Comment by steve-hodgkiss** [comment]
> If I'm understanding [django/django@242499f](https://github.com/django/django/commit/242499f2dc2bf24a9a5c855690a2e13d3303581a) correctly, it should be possible to efficiently get the first N (say, 1 or 2)

First couple would be fine. In 99% of uses cases a prefix is assigned to one location.

**Comment by cdwchriburg** [comment]
Looks like when this was implemented, it is using the location `display` attribute rather than the `name` attribute.  The `display` attribute contains the full location hierarchy path e.g. `Americas → United States → ATL01`.  The `name` attribute is just `ATL01`.

This results in an excessively long name to try and fit into a table view that has many columns. This makes line wrapping very likely and makes the data hard to read.  Can this be adjusted to use `location.name` instead of `location.display`?  I believe the previous functionality this change is replicating used the location name and not the full location hierarchy.

**Comment by glennmatthews** [comment]
Thanks for the feedback! The requested change is a bit tricky to do because of the generic/"automagical" way that #6450 does things. In *most* cases `display` is the correct attribute to use for related objects, it's just a few cases (such as `Location` and `VRF` -- as you've pointed out on #6637) where the `display` is more verbose than strictly necessary.

IMHO the generic `display` attribute is overloaded for too many purposes at present, as it's used for all of the following:

1. the title of each object's "detail" page
2. the default display of a reference to that object in various table views
3. the default display of a reference to that object in create/edit forms (see also #2668)
4. any number of one-off special cases as well

In 3.0 we should really think about separating these into distinct use cases and/or providing a way in each of these cases to explicitly override the `display` where it's either too brief or too verbose for a specific situation.
