### ISSUE TITLE
Module Interface Template substitution not working

### ISSUE THREAD

**Issue by gneville-ot** [nautobot/nautobot#6336]
### Environment
* Nautobot version (Docker tag too if applicable): 2.3.4
* Python version: 3.11
* Database platform, version: PG15
* Middleware(s): N/A

### Steps to Reproduce
1. Create Device Type, Parent/Child status: Parent, Create Module Bays xe-0/0/[0-31]
2. Create Device and associate to Device Type created in Step 1
3. Create Module Type
4. Edit Module Type from Step4, Add Interfaces, Use template: Name: `{module}`
5. Create Module, associate with Module Type from step 4 and then install in to device created in Step2 and any bay

### Expected Behavior
An interface is created with a name that mirrors the device's module bay name, e.g. xe-0/0/1

### Observed Behavior
An interface is created with a name of `{module}`

**Comment by gsnider2195** [comment]
Does your `ModuleBay` have the position field populated? This is the field that is required for this feature to work.

**Comment by glennmatthews** [comment]
Confirmed that this works correctly *if* the modulebay defines a `position`. If it has a `name` but no `position`, no substitution takes place.

**Comment by HanlinMiao** [comment]
Could be **breaking** but an alternative would be if the position is not set, just use the name with no position and never have an empty case for the name.

**Comment by gsnider2195** [comment]
We probably need better help text for the `ModuleBay.position` field and maybe even update the edit form to automatically fill in the `position` field as you type into the `name` field like we used to do with slugs? That would accomplish:
- Default the `position` to the same as the `name` if the user doesn't supply a `position`
- Bring it to the user's attention that if they don't update `position` it will default to the `name`
  - Encourage the user to pay closer attention the `position` field when creating a new ModuleBay. Since it's not a required field it's more likely to be ignored by a user who isn't familiar with the `ModuleBay` model
