### ISSUE TITLE
Bootstrap v3.4.1 vulnerability (CVE-2024-6485)

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot#6355]
### Environment
* Nautobot version (Docker tag too if applicable): 2.2.4
* Python version: 3.9.19
* Database platform, version:
* Middleware(s):

An application scanner (Blackduck) found that our Nautobot instance was using a version of Bootstrap (v3.4.1) that was vulnerable to CVE-2024-6485. The security team asked us to please upgrade to a non-vulnerable version such as v5.3.3.

Link to CVE details: https://nvd.nist.gov/vuln/detail/CVE-2024-6485

**Comment by bryanculver** [comment]
We assessed the code identified as vulnerable and determined that it is not currently used within Nautobot or our open source Apps. To our knowledge, we do not utilize the vulnerable feature in our core functionality, which suggests that we are not exposed to the risks associated with the CVE.

Exploiting the CVE requires a specific setup where combining untrusted input to the `data-*-text` on an HTML element, commonly a `<button>`, with the `.button()` method available in jQuery, to execute arbitrary code.

In our research, the only time `data-*-text` exists in the application is with the clipboard feature for copying things like device names and IP addresses but this tool does not use the vulnerable jQuery library. Additionally, Nautobot nor its Apps leverage the `.button()` method provided by jQuery.

We are working to migrate away from Bootstrap 3 but due to the heavy integration and vast ecosystem of Nautobot this will ultimately be a breaking change and we are carefully working to plan it.
