### ISSUE TITLE
Browsable REST API layout bugs

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#6414]
### Environment
* Nautobot version (Docker tag too if applicable): v2.3.8
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Open the browsable API
  a. https://demo.nautobot.com/api/
  b. https://demo.nautobot.com/api/circuits/  
  c. https://demo.nautobot.com/api/dcim/devices/
3. Observe the broken layout of the `method` and `url` box

### Expected Behavior

Something similar to the `retrieve` view:

https://demo.nautobot.com/api/dcim/devices/89b2ac3b-1853-4eeb-9ea6-6a081999bd3c/

![{6A56578F-B9BF-43EB-86CF-83BE7CDC050D}](https://github.com/user-attachments/assets/211d5f34-bdd4-4254-907a-be3f13fbcf7f)

### Observed Behavior

![{B9144AFF-1CFB-4826-9B0D-3AD8E99EA20C}](https://github.com/user-attachments/assets/568d1904-637d-413d-91ff-4f2f790c6335)

![{0B275F9F-F7FF-495B-81FE-0353BBBA9DDD}](https://github.com/user-attachments/assets/6d2f4978-e93f-4fbf-b003-137dfed23f47)

**Comment by HanlinMiao** [comment]
It seems like we are using the [base.html](https://github.com/encode/django-rest-framework/blob/d3dd45b3f48856c3513ab1eb5354194fa9898f39/rest_framework/templates/rest_framework/base.html) from django-rest-framework. And retrieve view does not have those layout problems because it does not have a [description](https://github.com/encode/django-rest-framework/blob/d3dd45b3f48856c3513ab1eb5354194fa9898f39/rest_framework/templates/rest_framework/base.html#L162-L164) and no [paginators](https://github.com/encode/django-rest-framework/blob/d3dd45b3f48856c3513ab1eb5354194fa9898f39/rest_framework/templates/rest_framework/base.html#L167-L171). Wonder if we could override that or if it is worth the effort.
