### ISSUE TITLE
Improve Load Times on IPAddress List View

### ISSUE THREAD

**Issue by brandomando** [nautobot/nautobot#6605]
### As ...

Nelly - Network Engineer

### I want ...

I want the IPAM - IP Address list view to load more efficiently

### So that ...

the view is more usable by network engineers who need to frequently access the IP Addresses table view for planning purposes.

### I know this is done when...

- Load times are reduced from 20-30 seconds to 5-6 seconds

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [X] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Apps (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [ ] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)

**Comment by brandomando** [comment]
Looking at this with @glennmatthews it was determined that the `COUNT` based columns of related objects are causing the delays in loading from the database.

**Comment by glennmatthews** [comment]
Specifically, as presently coded, we're always calculating a half dozen counts, even when those columns are hidden:

```
class IPAddressListView(generic.ObjectListView):
    queryset = IPAddress.objects.annotate(
        interface_count=count_related(Interface, "ip_addresses"),
        interface_parent_count=count_related(Device, "interfaces__ip_addresses", distinct=True),
        vm_interface_count=count_related(VMInterface, "ip_addresses"),
        vm_interface_parent_count=count_related(VirtualMachine, "interfaces__ip_addresses", distinct=True),
        assigned_count=count_related(Interface, "ip_addresses") + count_related(VMInterface, "ip_addresses"),
    )
```

A few ideas:
- Convert the first four counts to properly use `LinkedCountColumn` so that the count is only calculated when those columns are shown
- Since `assigned_count` is a sum of two different counts, this may not be addressable via the current `LinkedCountColumn` functionality, but we could maybe enhance the view's `alter_queryset()` so that at least it doesn't perform that calculation unless the table config would make said column visible?

**Comment by brandomando** [comment]
The `alter_queryset()` modification seems to make the most sense since we already have the two values from that field above in `interface_count` and `vm_interface_count`.
