### ISSUE TITLE
GraphQL Saved Queries Fail when `"` in the query

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot#703]
### Environment
* Python version: 3.7
* Nautobot version:  1.1.0-beta.2

### Steps to Reproduce
1. Create a query with quotes in it
2. Click on `Execute` on the right hand section of the page

```
query {
  sites(name: "Location2") {
    name
    circuit_terminations {
      circuit {
        cid
      }
    }
  }
}
```

### Expected Behavior

Query to run

### Observed Behavior

Error:

```
{
  "errors": [
    {
      "message": "Syntax Error GraphQL (2:15) Unexpected character \"&\".\n\n1: query {\n2:   sites(name: &quot;Location2&quot;) {\n                 ^\n3:     name\n",
      "locations": [
        {
          "line": 2,
          "column": 15
        }
      ]
    }
  ]
}
```

**Comment by jmcgill298** [comment]
I found the same issue. For clarity, this is not on the graphiql page, but when executing from within the `graphqlquery` view:  `extras/graphql-queiries/<slug>`

**Comment by FragmentedPacket** [comment]
Django is escaping the characters automatically due to it being within a Javascript block is my understanding. That means the quotes that are in the saved query turn into `&quot;`. I have #707 opened for a fix, but more or less a discussion to see what the best fix is since this is user provided data.

**Comment by dgarros** [comment]
Since we can easily jump to GraphiQL to execute the query with the `Open in GraphiQL` button , is it really worth it to have another option to execute the query directly ? The GraphiQL is interface is much better in my opinion

My preference would be to remove the response panel altogether from this page and maybe bring down the `Open in GraphiQL`  button to make it even more explicit

**Comment by jmcgill298** [comment]
IMO, I think it is nice to be able to do a quick validation that the query just saved is working as expected from the interface where it is created. I think these two interfaces (`execute` button and graphiql) serve different useful purposes.

I see the workflow as:
  * use graphiql to develop working query
  * save the query in nautobot
  * validate it is working as expected

The third step for me would be the `execute` button, and without that option, I would have to use some external tool to execute the query for validation.
