### ISSUE TITLE
Power Feeds and Power Panels buttons are swapped in menu

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot#759]
### Environment demo.nautobot.com
* Python version:
* Nautobot version: 1.1.0

### Steps to Reproduce
1. Log into Nautobot
2. Choose Power in Dropdown
3. Click on Power feed add button

### Expected Behavior
Clicking the Add button on Power Feed or Power Panel should take me to the
form page to add a Power Feed or Power Panel

### Observed Behavior
Clicking the Add button took me to the Import Page, and vice-versa.

**Comment by glennmatthews** [comment]
Thanks for the report and the pull request! I think this has been fixed in `next` (i.e. what will become 1.2.0) by https://github.com/nautobot/nautobot/pull/737/files#diff-ab949fb1e4b92187f41616d6dbb38f5706d3da797f8d99e238bec86d89db0b12, but it'll be good to have your PR fix it in 1.1.x as well. Thank you!
