### ISSUE TITLE
Show computed fields when listing objects

### ISSUE THREAD

**Issue by Thetacz** [nautobot/nautobot#894]
### Environment
* Python version: 3.6.8
* Nautobot version: v1.1.1

### Proposed Functionality
Show computed fields and allows filtering by their values in UI when listing objects of their associated model.

### Use Case
We want to give users a simple way of filtering whether IP is `public` or `private`. Since the algorithm to differentiate them is simple enough, we created computed field. But than we found there is no way to show them when listing existing IPs and no way to filter by them.

Given this is only 2 values, it would be nice to have drop down menu to select it by user when he want to use the filtering capability.

### Database Changes
Probably None

### External Dependencies
None

**Comment by glennmatthews** [comment]
Displaying computed fields in the list view should be pretty straightforward - we already do the same for custom fields - though performance might be an issue when the number of items displayed is set to a large value?
 
Allowing filtering/sorting by computed fields is a lot trickier because computed field values don't live in the database, and so they can't be directly queried against. We'd have to render all computed fields for all records and then search/sort/filter through them in Python, which would probably perform pretty poorly.

For this specific use case, it might be reasonably easy to implement a small plugin that basically just extends the existing list view with a couple of custom views and associated querysets (one for "public" and one for "private" IP address sets) - with the latest custom menus code these views could even be injected inline into the IPAM menu by the plugin.

Another option might be a small plugin that listens for the IPAddress `pre_save` signal and automatically sets an associated *custom* field to the desired value, which would then be filterable.

**Comment by glennmatthews** [comment]
Accepting this for just the list view display feature at this time.

**Comment by bryanculver** [comment]
Implemented with #1473
