### ISSUE TITLE
Invalid / Nonexistent Social Auth Causes 500 Error

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#963]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.3

### Steps to Reproduce
1. Enable a non-exist social auth backend or a simple typo (below should be `social_core.backends.google.GoogleOAuth2`)
```
AUTHENTICATION_BACKENDS = [
    "social_core.backends.google.GoogleOauth2",
    "nautobot.core.authentication.ObjectPermissionBackend",
]
```
2. Attempt to load Nautobot

### Expected Behavior
Fall back to default (local) authentication method

### Observed Behavior
500 and Nautobot doesn't load

![image](https://user-images.githubusercontent.com/29315002/135500678-a1df214f-603d-45e3-ad9a-19f6e7e8debf.png)

**Comment by jathanism** [comment]
After another review, we determined that this is working as intended because this is default behavior from the Django core:

https://github.com/django/django/blob/3.1.14/django/contrib/auth/__init__.py#L19-L20

```python
def load_backend(path):
    return import_string(path)()
```

Django attempts to import the backend class from the class path string, therefore it is an error to specify an invalid backend.

For us to wrap this behavior to falling back to local authentication could introduce potentially unwanted side effects in troubleshooting outside of asserting that configuration changes are the culprit. Lastly, we want to be very cautious about wrapping the default behaviors of the Django core with our own business logic, as that becomes very difficult to maintain over time.
