### ISSUE TITLE
`::1/128` is not a valid prefix

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot#969]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.3

When trying to create the prefix `::1/128` I get the following error:

```no-highlight
<class 'netaddr.core.AddrFormatError'>

invalid IPNetwork 0.0.0.1/128
```

Both Python netaddr and ipaddress modules see this as a valid IPNetwork.  

### Steps to Reproduce
1.  Create a prefix or aggregate using the prefix `::1/128`

### Expected Behavior

Prefix created

### Observed Behavior

```
invalid IPNetwork 0.0.0.1/128
```

**Comment by FragmentedPacket** [comment]
I dug into this and I don't know the solution, but what I can tell is that this is due to the `VarBinaryIPField` and how it gets stored in the DB as well as how it is extracted from the DB back into Python.

It will store the value in the DB for the IPv6 address as `b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'` which just equates to 1. There is no logic in `VarbinaryIPField` to know what family it needs to cast the binary to.

I get it to work for prefixes by adding the following to the `cidr_str` method on the `Prefix` model.

```python

    @property
    def cidr_str(self):
        if self.prefix_length is not None and self.prefix_length > 32 and "." in self.network:
            ip_address = netaddr.IPAddress(self.network)
            return "%s/%s" % (ip_address.ipv6(True), self.prefix_length)
        if self.network is not None and self.prefix_length is not None:
            return "%s/%s" % (self.network, self.prefix_length)
```

This resolves the whole loading bug that we were getting, but the utilization is now 100% which is different than the `0.0.0.1/32` that I have for a test for ipv4.

It also still renders `prefix.network` as `0.0.0.1/32` when accessing the attribute.

```python
>>> from nautobot.ipam.models import Prefix
>>> p = Prefix.objects.first()
>>> p
<Prefix: ::1/128>
>>> p.prefix.size
1
>>> p.get_child_ips()
<IPAddressQuerySet [<IPAddress: 0.0.0.1/32>]>
>>> Prefix.STATUS_CONTAINER
<Status: Container>
>>> p.vrf
>>> from nautobot.ipam.models import IPAddress
>>> p.prefix
IPNetwork('::1/128')
>>> IPAddress.objects.net_host_contained(p.prefix).filter(vrf=None)
<IPAddressQuerySet [<IPAddress: 0.0.0.1/32>]>
>>> p.prefix.broadcast
IPAddress('::1')
>>> p.network
'0.0.0.1'
>>> p.prefix.network
```

Hopefully this helps a little bit, but I don't know the best way to handle this in the long run. It would be great if we could determine within the `VarbinaryIPField` which family the IP should exist to (seems like it will most likely need to be via the `prefix_length` of the `Prefix` model.

**Comment by glennmatthews** [comment]
Thanks for the report and the investigation! I'm looking into this as well.
